/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/jacdac_slider.glb')
  return (
    <group ref={group} {...props} dispose={null}>

        <group name="JD_DATA"  position={[-25, 0, -10]}></group>
        <group name="JD_PWR"  position={[-25, 0, 10]}></group>
        <group name="JD_GND1" position={[25, 0, 10]}></group>
        <group name="JD_GND2" position={[25, 0, -10]}></group>

      <group name="jacdac-sliderwrl" userData={{ name: 'jacdac-slider.wrl' }}>
        <group name="Compound" scale={2.5399999619} userData={{ name: 'Compound' }}>
          <group name="Compound001" position={[-6.734251976, 0.3149606287, -2.6458268166]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Compound.001' }}>
            <mesh name="Compound002" geometry={nodes.Compound002.geometry} material={nodes.Compound002.material} userData={{ name: 'Compound.002' }} />
          </group>
          <group name="Compound003" position={[-4.9342517853, 0.3149606287, -2.6458268166]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Compound.003' }}>
            <mesh name="Compound004" geometry={nodes.Compound004.geometry} material={nodes.Compound004.material} userData={{ name: 'Compound.004' }} />
          </group>
          <group name="Compound005" position={[-1.765748024, 0.3149606287, 2.4900000095]} rotation={[-Math.PI, -4.64e-8, -Math.PI]} userData={{ name: 'Compound.005' }}>
            <mesh name="Compound006" geometry={nodes.Compound006.geometry} material={nodes.Compound006.material} userData={{ name: 'Compound.006' }} />
          </group>
          <group name="Compound007" position={[5.1977953911, 0.3149606287, -3.0434646606]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.007' }}>
            <mesh name="Compound008" geometry={nodes.Compound008.geometry} material={nodes.Compound008.material} userData={{ name: 'Compound.008' }} />
          </group>
          <group name="Compound009" position={[6.9153542519, 0.3149606287, -2.6537008286]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.009' }}>
            <mesh name="Compound010" geometry={nodes.Compound010.geometry} material={nodes.Compound010.material} userData={{ name: 'Compound.010' }} />
          </group>
          <group name="Compound011" position={[-5.8258266449, 0.3149606287, -3.0434646606]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.011' }}>
            <mesh name="Compound012" geometry={nodes.Compound012.geometry} material={nodes.Compound012.material} userData={{ name: 'Compound.012' }} />
          </group>
          <group name="Compound013" position={[6.115354538, 0.3149606287, -2.6537008286]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Compound.013' }}>
            <mesh name="Compound014" geometry={nodes.Compound014.geometry} material={nodes.Compound014.material} userData={{ name: 'Compound.014' }} />
          </group>
          <group name="Compound015" position={[6.5153541565, 0.3149606287, -2.6458268166]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.015' }}>
            <mesh name="Compound016" geometry={nodes.Compound016.geometry} material={nodes.Compound016.material} userData={{ name: 'Compound.016' }} />
          </group>
          <group name="Compound017" position={[-8.2726774216, 0.3149606287, 1.2441731691]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.017' }}>
            <mesh name="Compound018" geometry={nodes.Compound018.geometry} material={nodes.Compound018.material} userData={{ name: 'Compound.018' }} />
          </group>
          <group name="Compound019" position={[0.0796850398, 0.3149606287, 0.0900000036]} rotation={[-Math.PI, 4.64e-8, -Math.PI]} userData={{ name: 'Compound.019' }}>
            <group name="Compound020" userData={{ name: 'Compound.020' }}>
              <group name="Compound021" userData={{ name: 'Compound.021' }}>
                <group name="Compound022" userData={{ name: 'Compound.022' }}>
                  <mesh name="Compound009_1" geometry={nodes.Compound009_1.geometry} material={materials.mat_0} />
                  <mesh name="Compound009_2" geometry={nodes.Compound009_2.geometry} material={materials.mat_1} />
                  <mesh name="Compound009_3" geometry={nodes.Compound009_3.geometry} material={materials.mat_2} />
                </group>
                <mesh name="Compound023" geometry={nodes.Compound023.geometry} material={materials.mat_1} userData={{ name: 'Compound.023' }} />
                <mesh name="Compound024" geometry={nodes.Compound024.geometry} material={materials.mat_2} userData={{ name: 'Compound.024' }} />
                <mesh name="Compound025" geometry={nodes.Compound025.geometry} material={materials.mat_1} userData={{ name: 'Compound.025' }} />
                <mesh name="Compound026" geometry={nodes.Compound026.geometry} material={materials.mat_2} userData={{ name: 'Compound.026' }} />
                <mesh name="Compound027" geometry={nodes.Compound027.geometry} material={materials.mat_2} userData={{ name: 'Compound.027' }} />
                <mesh name="Compound028" geometry={nodes.Compound028.geometry} material={materials.mat_2} userData={{ name: 'Compound.028' }} />
                <mesh name="Compound029" geometry={nodes.Compound029.geometry} material={materials.mat_2} userData={{ name: 'Compound.029' }} />
                <mesh name="Compound030" geometry={nodes.Compound030.geometry} material={materials.mat_2} userData={{ name: 'Compound.030' }} />
                <mesh name="Compound031" geometry={nodes.Compound031.geometry} material={materials.mat_2} userData={{ name: 'Compound.031' }} />
                <mesh name="Compound032" geometry={nodes.Compound032.geometry} material={materials.mat_2} userData={{ name: 'Compound.032' }} />
                <mesh name="Compound033" geometry={nodes.Compound033.geometry} material={materials.mat_2} userData={{ name: 'Compound.033' }} />
                <mesh name="Compound034" geometry={nodes.Compound034.geometry} material={materials.mat_1} userData={{ name: 'Compound.034' }} />
                <mesh name="Compound035" geometry={nodes.Compound035.geometry} material={materials.mat_1} userData={{ name: 'Compound.035' }} />
                <mesh name="Compound036" geometry={nodes.Compound036.geometry} material={materials.mat_3} userData={{ name: 'Compound.036' }} />
                <mesh name="Compound037" geometry={nodes.Compound037.geometry} material={materials.mat_3} userData={{ name: 'Compound.037' }} />
                <mesh name="Compound038" geometry={nodes.Compound038.geometry} material={materials.mat_3} userData={{ name: 'Compound.038' }} />
                <mesh name="Compound039" geometry={nodes.Compound039.geometry} material={materials.mat_3} userData={{ name: 'Compound.039' }} />
                <mesh name="Compound040" geometry={nodes.Compound040.geometry} material={materials.mat_3} userData={{ name: 'Compound.040' }} />
                <mesh name="Compound041" geometry={nodes.Compound041.geometry} material={materials.mat_3} userData={{ name: 'Compound.041' }} />
                <mesh name="Compound042" geometry={nodes.Compound042.geometry} material={materials.mat_3} userData={{ name: 'Compound.042' }} />
                <mesh name="Compound043" geometry={nodes.Compound043.geometry} material={materials.mat_3} userData={{ name: 'Compound.043' }} />
                <mesh name="Compound044" geometry={nodes.Compound044.geometry} material={materials.mat_3} userData={{ name: 'Compound.044' }} />
                <mesh name="Compound045" geometry={nodes.Compound045.geometry} material={materials.mat_3} userData={{ name: 'Compound.045' }} />
                <mesh name="Compound046" geometry={nodes.Compound046.geometry} material={materials.mat_3} userData={{ name: 'Compound.046' }} />
                <mesh name="Compound047" geometry={nodes.Compound047.geometry} material={materials.mat_3} userData={{ name: 'Compound.047' }} />
                <mesh name="Compound048" geometry={nodes.Compound048.geometry} material={materials.mat_3} userData={{ name: 'Compound.048' }} />
                <mesh name="Compound049" geometry={nodes.Compound049.geometry} material={materials.mat_3} userData={{ name: 'Compound.049' }} />
                <mesh name="Compound050" geometry={nodes.Compound050.geometry} material={materials.mat_3} userData={{ name: 'Compound.050' }} />
                <mesh name="Compound051" geometry={nodes.Compound051.geometry} material={materials.mat_3} userData={{ name: 'Compound.051' }} />
                <mesh name="Compound052" geometry={nodes.Compound052.geometry} material={materials.mat_3} userData={{ name: 'Compound.052' }} />
                <mesh name="Compound053" geometry={nodes.Compound053.geometry} material={materials.mat_3} userData={{ name: 'Compound.053' }} />
                <mesh name="Compound054" geometry={nodes.Compound054.geometry} material={materials.mat_3} userData={{ name: 'Compound.054' }} />
                <mesh name="Compound055" geometry={nodes.Compound055.geometry} material={materials.mat_3} userData={{ name: 'Compound.055' }} />
                <mesh name="Compound056" geometry={nodes.Compound056.geometry} material={materials.mat_3} userData={{ name: 'Compound.056' }} />
                <mesh name="Compound057" geometry={nodes.Compound057.geometry} material={materials.mat_3} userData={{ name: 'Compound.057' }} />
                <mesh name="Compound058" geometry={nodes.Compound058.geometry} material={materials.mat_3} userData={{ name: 'Compound.058' }} />
                <mesh name="Compound059" geometry={nodes.Compound059.geometry} material={materials.mat_3} userData={{ name: 'Compound.059' }} />
                <mesh name="Compound060" geometry={nodes.Compound060.geometry} material={materials.mat_3} userData={{ name: 'Compound.060' }} />
                <mesh name="Compound061" geometry={nodes.Compound061.geometry} material={materials.mat_3} userData={{ name: 'Compound.061' }} />
                <mesh name="Compound062" geometry={nodes.Compound062.geometry} material={materials.mat_3} userData={{ name: 'Compound.062' }} />
                <mesh name="Compound063" geometry={nodes.Compound063.geometry} material={materials.mat_3} userData={{ name: 'Compound.063' }} />
                <mesh name="Compound064" geometry={nodes.Compound064.geometry} material={materials.mat_3} userData={{ name: 'Compound.064' }} />
                <mesh name="Compound065" geometry={nodes.Compound065.geometry} material={materials.mat_3} userData={{ name: 'Compound.065' }} />
                <mesh name="Compound066" geometry={nodes.Compound066.geometry} material={materials.mat_3} userData={{ name: 'Compound.066' }} />
                <mesh name="Compound067" geometry={nodes.Compound067.geometry} material={materials.mat_3} userData={{ name: 'Compound.067' }} />
                <mesh name="Compound068" geometry={nodes.Compound068.geometry} material={materials.mat_3} userData={{ name: 'Compound.068' }} />
                <mesh name="Compound069" geometry={nodes.Compound069.geometry} material={materials.mat_3} userData={{ name: 'Compound.069' }} />
                <mesh name="Compound070" geometry={nodes.Compound070.geometry} material={materials.mat_3} userData={{ name: 'Compound.070' }} />
                <mesh name="Compound071" geometry={nodes.Compound071.geometry} material={materials.mat_3} userData={{ name: 'Compound.071' }} />
                <mesh name="Compound072" geometry={nodes.Compound072.geometry} material={materials.mat_3} userData={{ name: 'Compound.072' }} />
                <mesh name="Compound073" geometry={nodes.Compound073.geometry} material={materials.mat_3} userData={{ name: 'Compound.073' }} />
                <mesh name="Compound074" geometry={nodes.Compound074.geometry} material={materials.mat_3} userData={{ name: 'Compound.074' }} />
                <mesh name="Compound075" geometry={nodes.Compound075.geometry} material={materials.mat_3} userData={{ name: 'Compound.075' }} />
                <mesh name="Compound076" geometry={nodes.Compound076.geometry} material={materials.mat_3} userData={{ name: 'Compound.076' }} />
                <mesh name="Compound077" geometry={nodes.Compound077.geometry} material={materials.mat_3} userData={{ name: 'Compound.077' }} />
                <mesh name="Compound078" geometry={nodes.Compound078.geometry} material={materials.mat_3} userData={{ name: 'Compound.078' }} />
                <mesh name="Compound079" geometry={nodes.Compound079.geometry} material={materials.mat_3} userData={{ name: 'Compound.079' }} />
                <mesh name="Compound080" geometry={nodes.Compound080.geometry} material={materials.mat_3} userData={{ name: 'Compound.080' }} />
                <mesh name="Compound081" geometry={nodes.Compound081.geometry} material={materials.mat_3} userData={{ name: 'Compound.081' }} />
                <mesh name="Compound082" geometry={nodes.Compound082.geometry} material={materials.mat_3} userData={{ name: 'Compound.082' }} />
                <mesh name="Compound083" geometry={nodes.Compound083.geometry} material={materials.mat_3} userData={{ name: 'Compound.083' }} />
                <mesh name="Compound084" geometry={nodes.Compound084.geometry} material={materials.mat_3} userData={{ name: 'Compound.084' }} />
                <mesh name="Compound085" geometry={nodes.Compound085.geometry} material={materials.mat_3} userData={{ name: 'Compound.085' }} />
                <mesh name="Compound086" geometry={nodes.Compound086.geometry} material={materials.mat_3} userData={{ name: 'Compound.086' }} />
                <mesh name="Compound087" geometry={nodes.Compound087.geometry} material={materials.mat_3} userData={{ name: 'Compound.087' }} />
                <mesh name="Compound088" geometry={nodes.Compound088.geometry} material={materials.mat_3} userData={{ name: 'Compound.088' }} />
                <mesh name="Compound089" geometry={nodes.Compound089.geometry} material={materials.mat_3} userData={{ name: 'Compound.089' }} />
                <mesh name="Compound090" geometry={nodes.Compound090.geometry} material={materials.mat_3} userData={{ name: 'Compound.090' }} />
                <mesh name="Compound091" geometry={nodes.Compound091.geometry} material={materials.mat_3} userData={{ name: 'Compound.091' }} />
                <mesh name="Compound092" geometry={nodes.Compound092.geometry} material={materials.mat_3} userData={{ name: 'Compound.092' }} />
                <mesh name="Compound093" geometry={nodes.Compound093.geometry} material={materials.mat_3} userData={{ name: 'Compound.093' }} />
              </group>
            </group>
          </group>
          <group name="Compound094" position={[8.4240159988, 0.3149606287, 0.0551968515]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.094' }}>
            <mesh name="Compound095" geometry={nodes.Compound095.geometry} material={nodes.Compound095.material} userData={{ name: 'Compound.095' }} />
          </group>
          <group name="Compound096" position={[0.0812598467, 0.3149606287, 3.2400000095]} userData={{ name: 'Compound.096' }}>
            <group name="Compound097" userData={{ name: 'Compound.097' }}>
              <group name="Compound098" userData={{ name: 'Compound.098' }}>
                <group name="Compound099" userData={{ name: 'Compound.099' }}>
                  <mesh name="Compound082_1" geometry={nodes.Compound082_1.geometry} material={materials.mat_4} />
                  <mesh name="Compound082_2" geometry={nodes.Compound082_2.geometry} material={materials.mat_5} />
                  <mesh name="Compound082_3" geometry={nodes.Compound082_3.geometry} material={materials.mat_6} />
                </group>
                <mesh name="Compound100" geometry={nodes.Compound100.geometry} material={materials.mat_4} userData={{ name: 'Compound.100' }} />
                <mesh name="Compound101" geometry={nodes.Compound101.geometry} material={materials.mat_4} userData={{ name: 'Compound.101' }} />
                <mesh name="Compound102" geometry={nodes.Compound102.geometry} material={materials.mat_4} userData={{ name: 'Compound.102' }} />
                <mesh name="Compound103" geometry={nodes.Compound103.geometry} material={materials.mat_4} userData={{ name: 'Compound.103' }} />
                <mesh name="Compound104" geometry={nodes.Compound104.geometry} material={materials.mat_4} userData={{ name: 'Compound.104' }} />
                <mesh name="Compound105" geometry={nodes.Compound105.geometry} material={materials.mat_5} userData={{ name: 'Compound.105' }} />
                <mesh name="Compound106" geometry={nodes.Compound106.geometry} material={materials.mat_4} userData={{ name: 'Compound.106' }} />
                <mesh name="Compound107" geometry={nodes.Compound107.geometry} material={materials.mat_5} userData={{ name: 'Compound.107' }} />
                <mesh name="Compound108" geometry={nodes.Compound108.geometry} material={materials.mat_4} userData={{ name: 'Compound.108' }} />
                <mesh name="Compound109" geometry={nodes.Compound109.geometry} material={materials.mat_4} userData={{ name: 'Compound.109' }} />
                <mesh name="Compound110" geometry={nodes.Compound110.geometry} material={materials.mat_4} userData={{ name: 'Compound.110' }} />
                <mesh name="Compound111" geometry={nodes.Compound111.geometry} material={materials.mat_4} userData={{ name: 'Compound.111' }} />
                <mesh name="Compound112" geometry={nodes.Compound112.geometry} material={materials.mat_4} userData={{ name: 'Compound.112' }} />
                <mesh name="Compound113" geometry={nodes.Compound113.geometry} material={materials.mat_4} userData={{ name: 'Compound.113' }} />
                <mesh name="Compound114" geometry={nodes.Compound114.geometry} material={materials.mat_4} userData={{ name: 'Compound.114' }} />
                <mesh name="Compound115" geometry={nodes.Compound115.geometry} material={materials.mat_5} userData={{ name: 'Compound.115' }} />
                <mesh name="Compound116" geometry={nodes.Compound116.geometry} material={materials.mat_5} userData={{ name: 'Compound.116' }} />
                <mesh name="Compound117" geometry={nodes.Compound117.geometry} material={materials.mat_5} userData={{ name: 'Compound.117' }} />
                <mesh name="Compound118" geometry={nodes.Compound118.geometry} material={materials.mat_5} userData={{ name: 'Compound.118' }} />
                <mesh name="Compound119" geometry={nodes.Compound119.geometry} material={materials.mat_5} userData={{ name: 'Compound.119' }} />
                <mesh name="Compound120" geometry={nodes.Compound120.geometry} material={materials.mat_4} userData={{ name: 'Compound.120' }} />
                <mesh name="Compound121" geometry={nodes.Compound121.geometry} material={materials.mat_5} userData={{ name: 'Compound.121' }} />
                <mesh name="Compound122" geometry={nodes.Compound122.geometry} material={materials.mat_4} userData={{ name: 'Compound.122' }} />
                <mesh name="Compound123" geometry={nodes.Compound123.geometry} material={materials.mat_4} userData={{ name: 'Compound.123' }} />
                <mesh name="Compound124" geometry={nodes.Compound124.geometry} material={materials.mat_5} userData={{ name: 'Compound.124' }} />
                <mesh name="Compound125" geometry={nodes.Compound125.geometry} material={materials.mat_5} userData={{ name: 'Compound.125' }} />
                <mesh name="Compound126" geometry={nodes.Compound126.geometry} material={materials.mat_5} userData={{ name: 'Compound.126' }} />
                <mesh name="Compound127" geometry={nodes.Compound127.geometry} material={materials.mat_5} userData={{ name: 'Compound.127' }} />
                <mesh name="Compound128" geometry={nodes.Compound128.geometry} material={materials.mat_5} userData={{ name: 'Compound.128' }} />
                <mesh name="Compound129" geometry={nodes.Compound129.geometry} material={materials.mat_4} userData={{ name: 'Compound.129' }} />
                <mesh name="Compound130" geometry={nodes.Compound130.geometry} material={materials.mat_5} userData={{ name: 'Compound.130' }} />
                <mesh name="Compound131" geometry={nodes.Compound131.geometry} material={materials.mat_5} userData={{ name: 'Compound.131' }} />
                <mesh name="Compound132" geometry={nodes.Compound132.geometry} material={materials.mat_5} userData={{ name: 'Compound.132' }} />
                <mesh name="Compound133" geometry={nodes.Compound133.geometry} material={materials.mat_5} userData={{ name: 'Compound.133' }} />
                <mesh name="Compound134" geometry={nodes.Compound134.geometry} material={materials.mat_5} userData={{ name: 'Compound.134' }} />
                <mesh name="Compound135" geometry={nodes.Compound135.geometry} material={materials.mat_5} userData={{ name: 'Compound.135' }} />
                <mesh name="Compound136" geometry={nodes.Compound136.geometry} material={materials.mat_4} userData={{ name: 'Compound.136' }} />
                <mesh name="Compound137" geometry={nodes.Compound137.geometry} material={materials.mat_5} userData={{ name: 'Compound.137' }} />
                <mesh name="Compound138" geometry={nodes.Compound138.geometry} material={materials.mat_4} userData={{ name: 'Compound.138' }} />
                <mesh name="Compound139" geometry={nodes.Compound139.geometry} material={materials.mat_4} userData={{ name: 'Compound.139' }} />
                <mesh name="Compound140" geometry={nodes.Compound140.geometry} material={materials.mat_4} userData={{ name: 'Compound.140' }} />
                <mesh name="Compound141" geometry={nodes.Compound141.geometry} material={materials.mat_5} userData={{ name: 'Compound.141' }} />
                <mesh name="Compound142" geometry={nodes.Compound142.geometry} material={materials.mat_4} userData={{ name: 'Compound.142' }} />
                <mesh name="Compound143" geometry={nodes.Compound143.geometry} material={materials.mat_4} userData={{ name: 'Compound.143' }} />
                <mesh name="Compound144" geometry={nodes.Compound144.geometry} material={materials.mat_4} userData={{ name: 'Compound.144' }} />
                <mesh name="Compound145" geometry={nodes.Compound145.geometry} material={materials.mat_4} userData={{ name: 'Compound.145' }} />
                <mesh name="Compound146" geometry={nodes.Compound146.geometry} material={materials.mat_5} userData={{ name: 'Compound.146' }} />
                <mesh name="Compound147" geometry={nodes.Compound147.geometry} material={materials.mat_5} userData={{ name: 'Compound.147' }} />
                <mesh name="Compound148" geometry={nodes.Compound148.geometry} material={materials.mat_5} userData={{ name: 'Compound.148' }} />
                <mesh name="Compound149" geometry={nodes.Compound149.geometry} material={materials.mat_5} userData={{ name: 'Compound.149' }} />
                <mesh name="Compound150" geometry={nodes.Compound150.geometry} material={materials.mat_5} userData={{ name: 'Compound.150' }} />
                <mesh name="Compound151" geometry={nodes.Compound151.geometry} material={materials.mat_5} userData={{ name: 'Compound.151' }} />
                <mesh name="Compound152" geometry={nodes.Compound152.geometry} material={materials.mat_4} userData={{ name: 'Compound.152' }} />
                <mesh name="Compound153" geometry={nodes.Compound153.geometry} material={materials.mat_4} userData={{ name: 'Compound.153' }} />
                <mesh name="Compound154" geometry={nodes.Compound154.geometry} material={materials.mat_4} userData={{ name: 'Compound.154' }} />
                <mesh name="Compound155" geometry={nodes.Compound155.geometry} material={materials.mat_4} userData={{ name: 'Compound.155' }} />
                <mesh name="Compound156" geometry={nodes.Compound156.geometry} material={materials.mat_4} userData={{ name: 'Compound.156' }} />
                <mesh name="Compound157" geometry={nodes.Compound157.geometry} material={materials.mat_4} userData={{ name: 'Compound.157' }} />
                <mesh name="Compound158" geometry={nodes.Compound158.geometry} material={materials.mat_4} userData={{ name: 'Compound.158' }} />
                <mesh name="Compound159" geometry={nodes.Compound159.geometry} material={materials.mat_4} userData={{ name: 'Compound.159' }} />
                <mesh name="Compound160" geometry={nodes.Compound160.geometry} material={materials.mat_4} userData={{ name: 'Compound.160' }} />
                <mesh name="Compound161" geometry={nodes.Compound161.geometry} material={materials.mat_4} userData={{ name: 'Compound.161' }} />
                <mesh name="Compound162" geometry={nodes.Compound162.geometry} material={materials.mat_4} userData={{ name: 'Compound.162' }} />
                <mesh name="Compound163" geometry={nodes.Compound163.geometry} material={materials.mat_5} userData={{ name: 'Compound.163' }} />
                <mesh name="Compound164" geometry={nodes.Compound164.geometry} material={materials.mat_5} userData={{ name: 'Compound.164' }} />
                <mesh name="Compound165" geometry={nodes.Compound165.geometry} material={materials.mat_5} userData={{ name: 'Compound.165' }} />
                <mesh name="Compound166" geometry={nodes.Compound166.geometry} material={materials.mat_5} userData={{ name: 'Compound.166' }} />
                <mesh name="Compound167" geometry={nodes.Compound167.geometry} material={materials.mat_4} userData={{ name: 'Compound.167' }} />
                <mesh name="Compound168" geometry={nodes.Compound168.geometry} material={materials.mat_4} userData={{ name: 'Compound.168' }} />
                <mesh name="Compound169" geometry={nodes.Compound169.geometry} material={materials.mat_5} userData={{ name: 'Compound.169' }} />
                <mesh name="Compound170" geometry={nodes.Compound170.geometry} material={materials.mat_5} userData={{ name: 'Compound.170' }} />
                <mesh name="Compound171" geometry={nodes.Compound171.geometry} material={materials.mat_4} userData={{ name: 'Compound.171' }} />
                <mesh name="Compound172" geometry={nodes.Compound172.geometry} material={materials.mat_4} userData={{ name: 'Compound.172' }} />
                <mesh name="Compound173" geometry={nodes.Compound173.geometry} material={materials.mat_5} userData={{ name: 'Compound.173' }} />
                <mesh name="Compound174" geometry={nodes.Compound174.geometry} material={materials.mat_5} userData={{ name: 'Compound.174' }} />
                <mesh name="Compound175" geometry={nodes.Compound175.geometry} material={materials.mat_5} userData={{ name: 'Compound.175' }} />
                <mesh name="Compound176" geometry={nodes.Compound176.geometry} material={materials.mat_4} userData={{ name: 'Compound.176' }} />
                <mesh name="Compound177" geometry={nodes.Compound177.geometry} material={materials.mat_4} userData={{ name: 'Compound.177' }} />
                <mesh name="Compound178" geometry={nodes.Compound178.geometry} material={materials.mat_4} userData={{ name: 'Compound.178' }} />
                <mesh name="Compound179" geometry={nodes.Compound179.geometry} material={materials.mat_4} userData={{ name: 'Compound.179' }} />
                <mesh name="Compound180" geometry={nodes.Compound180.geometry} material={materials.mat_4} userData={{ name: 'Compound.180' }} />
                <mesh name="Compound181" geometry={nodes.Compound181.geometry} material={materials.mat_4} userData={{ name: 'Compound.181' }} />
                <mesh name="Compound182" geometry={nodes.Compound182.geometry} material={materials.mat_4} userData={{ name: 'Compound.182' }} />
                <mesh name="Compound183" geometry={nodes.Compound183.geometry} material={materials.mat_4} userData={{ name: 'Compound.183' }} />
                <mesh name="Compound184" geometry={nodes.Compound184.geometry} material={materials.mat_4} userData={{ name: 'Compound.184' }} />
                <mesh name="Compound185" geometry={nodes.Compound185.geometry} material={materials.mat_4} userData={{ name: 'Compound.185' }} />
                <mesh name="Compound186" geometry={nodes.Compound186.geometry} material={materials.mat_4} userData={{ name: 'Compound.186' }} />
                <mesh name="Compound187" geometry={nodes.Compound187.geometry} material={materials.mat_4} userData={{ name: 'Compound.187' }} />
                <mesh name="Compound188" geometry={nodes.Compound188.geometry} material={materials.mat_4} userData={{ name: 'Compound.188' }} />
                <mesh name="Compound189" geometry={nodes.Compound189.geometry} material={materials.mat_4} userData={{ name: 'Compound.189' }} />
                <mesh name="Compound190" geometry={nodes.Compound190.geometry} material={materials.mat_4} userData={{ name: 'Compound.190' }} />
                <mesh name="Compound191" geometry={nodes.Compound191.geometry} material={materials.mat_4} userData={{ name: 'Compound.191' }} />
                <mesh name="Compound192" geometry={nodes.Compound192.geometry} material={materials.mat_5} userData={{ name: 'Compound.192' }} />
                <mesh name="Compound193" geometry={nodes.Compound193.geometry} material={materials.mat_5} userData={{ name: 'Compound.193' }} />
                <mesh name="Compound194" geometry={nodes.Compound194.geometry} material={materials.mat_5} userData={{ name: 'Compound.194' }} />
                <mesh name="Compound195" geometry={nodes.Compound195.geometry} material={materials.mat_5} userData={{ name: 'Compound.195' }} />
                <mesh name="Compound196" geometry={nodes.Compound196.geometry} material={materials.mat_5} userData={{ name: 'Compound.196' }} />
                <mesh name="Compound197" geometry={nodes.Compound197.geometry} material={materials.mat_5} userData={{ name: 'Compound.197' }} />
                <mesh name="Compound198" geometry={nodes.Compound198.geometry} material={materials.mat_6} userData={{ name: 'Compound.198' }} />
                <mesh name="Compound199" geometry={nodes.Compound199.geometry} material={materials.mat_5} userData={{ name: 'Compound.199' }} />
                <mesh name="Compound200" geometry={nodes.Compound200.geometry} material={materials.mat_5} userData={{ name: 'Compound.200' }} />
                <mesh name="Compound201" geometry={nodes.Compound201.geometry} material={materials.mat_5} userData={{ name: 'Compound.201' }} />
                <mesh name="Compound202" geometry={nodes.Compound202.geometry} material={materials.mat_4} userData={{ name: 'Compound.202' }} />
                <mesh name="Compound203" geometry={nodes.Compound203.geometry} material={materials.mat_4} userData={{ name: 'Compound.203' }} />
                <mesh name="Compound204" geometry={nodes.Compound204.geometry} material={materials.mat_5} userData={{ name: 'Compound.204' }} />
                <mesh name="Compound205" geometry={nodes.Compound205.geometry} material={materials.mat_4} userData={{ name: 'Compound.205' }} />
                <mesh name="Compound206" geometry={nodes.Compound206.geometry} material={materials.mat_4} userData={{ name: 'Compound.206' }} />
                <mesh name="Compound207" geometry={nodes.Compound207.geometry} material={materials.mat_4} userData={{ name: 'Compound.207' }} />
                <mesh name="Compound208" geometry={nodes.Compound208.geometry} material={materials.mat_4} userData={{ name: 'Compound.208' }} />
                <mesh name="Compound209" geometry={nodes.Compound209.geometry} material={materials.mat_5} userData={{ name: 'Compound.209' }} />
                <mesh name="Compound210" geometry={nodes.Compound210.geometry} material={materials.mat_4} userData={{ name: 'Compound.210' }} />
                <mesh name="Compound211" geometry={nodes.Compound211.geometry} material={materials.mat_4} userData={{ name: 'Compound.211' }} />
                <mesh name="Compound212" geometry={nodes.Compound212.geometry} material={materials.mat_5} userData={{ name: 'Compound.212' }} />
                <mesh name="Compound213" geometry={nodes.Compound213.geometry} material={materials.mat_4} userData={{ name: 'Compound.213' }} />
                <mesh name="Compound214" geometry={nodes.Compound214.geometry} material={materials.mat_4} userData={{ name: 'Compound.214' }} />
                <mesh name="Compound215" geometry={nodes.Compound215.geometry} material={materials.mat_4} userData={{ name: 'Compound.215' }} />
                <mesh name="Compound216" geometry={nodes.Compound216.geometry} material={materials.mat_4} userData={{ name: 'Compound.216' }} />
                <mesh name="Compound217" geometry={nodes.Compound217.geometry} material={materials.mat_5} userData={{ name: 'Compound.217' }} />
                <mesh name="Compound218" geometry={nodes.Compound218.geometry} material={materials.mat_5} userData={{ name: 'Compound.218' }} />
                <mesh name="Compound219" geometry={nodes.Compound219.geometry} material={materials.mat_4} userData={{ name: 'Compound.219' }} />
                <mesh name="Compound220" geometry={nodes.Compound220.geometry} material={materials.mat_4} userData={{ name: 'Compound.220' }} />
                <mesh name="Compound221" geometry={nodes.Compound221.geometry} material={materials.mat_4} userData={{ name: 'Compound.221' }} />
                <mesh name="Compound222" geometry={nodes.Compound222.geometry} material={materials.mat_4} userData={{ name: 'Compound.222' }} />
                <mesh name="Compound223" geometry={nodes.Compound223.geometry} material={materials.mat_6} userData={{ name: 'Compound.223' }} />
                <mesh name="Compound224" geometry={nodes.Compound224.geometry} material={materials.mat_4} userData={{ name: 'Compound.224' }} />
                <mesh name="Compound225" geometry={nodes.Compound225.geometry} material={materials.mat_4} userData={{ name: 'Compound.225' }} />
                <mesh name="Compound226" geometry={nodes.Compound226.geometry} material={materials.mat_4} userData={{ name: 'Compound.226' }} />
                <mesh name="Compound227" geometry={nodes.Compound227.geometry} material={materials.mat_4} userData={{ name: 'Compound.227' }} />
                <mesh name="Compound228" geometry={nodes.Compound228.geometry} material={materials.mat_4} userData={{ name: 'Compound.228' }} />
                <mesh name="Compound229" geometry={nodes.Compound229.geometry} material={materials.mat_4} userData={{ name: 'Compound.229' }} />
                <mesh name="Compound230" geometry={nodes.Compound230.geometry} material={materials.mat_4} userData={{ name: 'Compound.230' }} />
                <mesh name="Compound231" geometry={nodes.Compound231.geometry} material={materials.mat_4} userData={{ name: 'Compound.231' }} />
                <mesh name="Compound232" geometry={nodes.Compound232.geometry} material={materials.mat_4} userData={{ name: 'Compound.232' }} />
                <mesh name="Compound233" geometry={nodes.Compound233.geometry} material={materials.mat_4} userData={{ name: 'Compound.233' }} />
                <mesh name="Compound234" geometry={nodes.Compound234.geometry} material={materials.mat_4} userData={{ name: 'Compound.234' }} />
                <mesh name="Compound235" geometry={nodes.Compound235.geometry} material={materials.mat_4} userData={{ name: 'Compound.235' }} />
                <mesh name="Compound236" geometry={nodes.Compound236.geometry} material={materials.mat_4} userData={{ name: 'Compound.236' }} />
                <mesh name="Compound237" geometry={nodes.Compound237.geometry} material={materials.mat_4} userData={{ name: 'Compound.237' }} />
                <mesh name="Compound238" geometry={nodes.Compound238.geometry} material={materials.mat_4} userData={{ name: 'Compound.238' }} />
                <mesh name="Compound239" geometry={nodes.Compound239.geometry} material={materials.mat_4} userData={{ name: 'Compound.239' }} />
                <mesh name="Compound240" geometry={nodes.Compound240.geometry} material={materials.mat_4} userData={{ name: 'Compound.240' }} />
                <mesh name="Compound241" geometry={nodes.Compound241.geometry} material={materials.mat_4} userData={{ name: 'Compound.241' }} />
                <mesh name="Compound242" geometry={nodes.Compound242.geometry} material={materials.mat_4} userData={{ name: 'Compound.242' }} />
                <mesh name="Compound243" geometry={nodes.Compound243.geometry} material={materials.mat_4} userData={{ name: 'Compound.243' }} />
                <mesh name="Compound244" geometry={nodes.Compound244.geometry} material={materials.mat_4} userData={{ name: 'Compound.244' }} />
                <mesh name="Compound245" geometry={nodes.Compound245.geometry} material={materials.mat_4} userData={{ name: 'Compound.245' }} />
                <mesh name="Compound246" geometry={nodes.Compound246.geometry} material={materials.mat_4} userData={{ name: 'Compound.246' }} />
                <mesh name="Compound247" geometry={nodes.Compound247.geometry} material={materials.mat_4} userData={{ name: 'Compound.247' }} />
                <mesh name="Compound248" geometry={nodes.Compound248.geometry} material={materials.mat_4} userData={{ name: 'Compound.248' }} />
                <mesh name="Compound249" geometry={nodes.Compound249.geometry} material={materials.mat_4} userData={{ name: 'Compound.249' }} />
                <mesh name="Compound250" geometry={nodes.Compound250.geometry} material={materials.mat_4} userData={{ name: 'Compound.250' }} />
                <mesh name="Compound251" geometry={nodes.Compound251.geometry} material={materials.mat_4} userData={{ name: 'Compound.251' }} />
                <mesh name="Compound252" geometry={nodes.Compound252.geometry} material={materials.mat_4} userData={{ name: 'Compound.252' }} />
                <mesh name="Compound253" geometry={nodes.Compound253.geometry} material={materials.mat_4} userData={{ name: 'Compound.253' }} />
                <mesh name="Compound254" geometry={nodes.Compound254.geometry} material={materials.mat_4} userData={{ name: 'Compound.254' }} />
                <mesh name="Compound255" geometry={nodes.Compound255.geometry} material={materials.mat_4} userData={{ name: 'Compound.255' }} />
              </group>
            </group>
          </group>
          <group name="Compound256" position={[8.4240159988, 0.3149606287, -1.1180315018]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Compound.256' }}>
            <mesh name="Compound257" geometry={nodes.Compound257.geometry} material={nodes.Compound257.material} userData={{ name: 'Compound.257' }} />
          </group>
          <group name="Compound258" position={[-1.765748024, 0.3149606287, 3.9860630035]} rotation={[-Math.PI, -4.64e-8, -Math.PI]} userData={{ name: 'Compound.258' }}>
            <mesh name="Compound259" geometry={nodes.Compound259.geometry} material={nodes.Compound259.material} userData={{ name: 'Compound.259' }} />
          </group>
          <group name="Compound260" position={[-8.2726774216, 0.3149606287, 0.0709448829]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Compound.260' }}>
            <mesh name="Compound261" geometry={nodes.Compound261.geometry} material={nodes.Compound261.material} userData={{ name: 'Compound.261' }} />
          </group>
          <mesh name="Compound262" geometry={nodes.Compound262.geometry} material={materials.mat_7} userData={{ name: 'Compound.262' }} />
          <mesh name="Face" geometry={nodes.Face.geometry} material={materials.mat_8} userData={{ name: 'Face' }} />
          <mesh name="Face001" geometry={nodes.Face001.geometry} material={materials.mat_9} userData={{ name: 'Face.001' }} />
          <mesh name="Face002" geometry={nodes.Face002.geometry} material={materials.mat_10} userData={{ name: 'Face.002' }} />
          <mesh name="Face003" geometry={nodes.Face003.geometry} material={materials.mat_8} userData={{ name: 'Face.003' }} />
          <mesh name="Face004" geometry={nodes.Face004.geometry} material={materials.mat_10} userData={{ name: 'Face.004' }} />
          <mesh name="Face005" geometry={nodes.Face005.geometry} material={materials.mat_11} userData={{ name: 'Face.005' }} />
          <mesh name="Face006" geometry={nodes.Face006.geometry} material={materials.mat_11} userData={{ name: 'Face.006' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/jacdac_slider.glb')
