/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Jacdac_RGBLED.gltf')
  // eslint-disable-next-line react/prop-types
  
  return (
    <group ref={group} {...props} dispose={null} >
      <group
        name="PCB"
        scale={1000}
        userData={{
          name: 'PCB',
          JD_PWR: [{ x: -9.95, y: 10.05 }],
          JD_DATA: [{ x: 9.95, y: 10.05 }],
          JD_GND: [
            { x: -9.95, y: -10.05 },
            { x: 9.95, y: -10.05 },
          ],
        }}>

      <group name="JD_PWR"  position={[-0.00995, 0, 0.01005]}>

      </group>
      <group name="JD_DATA"  position={[0.00995, 0, 0.01005]}>

      </group>
      <group name="JD_GND1" position={[-0.00995, 0, -0.01005]}></group>
      <group name="JD_GND2" position={[0.00995, 0, -0.01005]}></group>
        <group name="100" userData={{ name: '100' }}>
          <group name="99" position={[-0.0022998785, 0, 0.0065499209]} rotation={[-Math.PI, -8.74e-8, -Math.PI]} userData={{ name: '99' }}>
            <mesh name="MSRC-RCLAMP0521P-N_v2" geometry={nodes['MSRC-RCLAMP0521P-N_v2'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2'].material} />
            <mesh name="MSRC-RCLAMP0521P-N_v2_1" geometry={nodes['MSRC-RCLAMP0521P-N_v2_1'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2_1'].material} />
          </group>
        </group>
        <group name="102" userData={{ name: '102' }}>
          <group name="101" position={[0.0022998834, 0, 0.0065500829]} userData={{ name: '101' }}>
            <mesh name="MSRC-RCLAMP0521P-N_v2001" geometry={nodes['MSRC-RCLAMP0521P-N_v2001'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2001'].material} />
            <mesh name="MSRC-RCLAMP0521P-N_v2001_1" geometry={nodes['MSRC-RCLAMP0521P-N_v2001_1'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2001_1'].material} />
          </group>
        </group>
        <group name="104" userData={{ name: '104' }}>
          <group name="103" position={[0, 0, -0.0064999182]} userData={{ name: '103' }}>
            <mesh name="MSRC-0603_LED_Orange001" geometry={nodes['MSRC-0603_LED_Orange001'].geometry} material={nodes['MSRC-0603_LED_Orange001'].material} />
            <mesh name="MSRC-0603_LED_Orange001_1" geometry={nodes['MSRC-0603_LED_Orange001_1'].geometry} material={nodes['MSRC-0603_LED_Orange001_1'].material} />
            <mesh name="MSRC-0603_LED_Orange001_2" geometry={nodes['MSRC-0603_LED_Orange001_2'].geometry} material={nodes['MSRC-0603_LED_Orange001_2'].material} />
            <mesh name="MSRC-0603_LED_Orange001_3" geometry={nodes['MSRC-0603_LED_Orange001_3'].geometry} material={nodes['MSRC-0603_LED_Orange001_3'].material} />
            <mesh name="MSRC-0603_LED_Orange001_4" geometry={nodes['MSRC-0603_LED_Orange001_4'].geometry} material={nodes['MSRC-0603_LED_Orange001_4'].material} />
          </group>
        </group>
        <group name="106" userData={{ name: '106' }}>
          <group name="105" position={[-0.0064499183, 0, 0.0021457879]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '105' }}>
            <mesh name="TSSOP20_STM" geometry={nodes.TSSOP20_STM.geometry} material={materials.mat_13} />
            <mesh name="TSSOP20_STM_1" geometry={nodes.TSSOP20_STM_1.geometry} material={materials.mat_14} />
            <mesh name="TSSOP20_STM_2" geometry={nodes.TSSOP20_STM_2.geometry} material={nodes.TSSOP20_STM_2.material} />
          </group>
        </group>
        <group name="108" userData={{ name: '108' }}>
          <group name="107" position={[0.0021775537, 0, 0.0041845129]} rotation={[0, Math.PI / 2, 0]} userData={{ name: '107' }}>
            <mesh name="MSRC-SOT23-5" geometry={nodes['MSRC-SOT23-5'].geometry} material={nodes['MSRC-SOT23-5'].material} />
            <mesh name="MSRC-SOT23-5_1" geometry={nodes['MSRC-SOT23-5_1'].geometry} material={nodes['MSRC-SOT23-5_1'].material} />
            <mesh name="MSRC-SOT23-5_2" geometry={nodes['MSRC-SOT23-5_2'].geometry} material={nodes['MSRC-SOT23-5_2'].material} />
            <mesh name="MSRC-SOT23-5_3" geometry={nodes['MSRC-SOT23-5_3'].geometry} material={nodes['MSRC-SOT23-5_3'].material} />
          </group>
        </group>
        <group name="110" userData={{ name: '110' }}>
          <group name="109" position={[-0.0057998784, 0, -0.0062001213]} userData={{ name: '109' }}>
            <mesh name="RC0603N004" geometry={nodes.RC0603N004.geometry} material={nodes.RC0603N004.material} />
            <mesh name="RC0603N004_1" geometry={nodes.RC0603N004_1.geometry} material={nodes.RC0603N004_1.material} />
          </group>
        </group>
        <group name="112" userData={{ name: '112' }}>
          <group name="111" position={[0.0001723352, 0, -0.0042248769]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '111' }}>
            <mesh name="RC0603N005" geometry={nodes.RC0603N005.geometry} material={nodes.RC0603N005.material} />
            <mesh name="RC0603N005_1" geometry={nodes.RC0603N005_1.geometry} material={nodes.RC0603N005_1.material} />
          </group>
        </group>
        <group name="118" userData={{ name: '118' }}>
          <group name="114" position={[0.0031069361, 0, -0.0041935979]} userData={{ name: '114' }}>
            <mesh name="16" geometry={nodes['16'].geometry} material={materials.mat_17} userData={{ name: '16' }} />
          </group>
          <group name="116" position={[0.0031069361, 0, -0.0048285965]} userData={{ name: '116' }}>
            <mesh name="17" geometry={nodes['17'].geometry} material={nodes['17'].material} userData={{ name: '17' }} />
          </group>
          <group name="117" position={[0.0031069361, 0, -0.0035585961]} userData={{ name: '117' }}>
            <mesh name="17001" geometry={nodes['17001'].geometry} material={nodes['17001'].material} userData={{ name: '17.001' }} />
          </group>
        </group>
        <group name="120" userData={{ name: '120' }}>
          <group name="119" position={[0.0022998834, 0, -0.0064999182]} userData={{ name: '119' }}>
            <mesh name="MSRC-RCLAMP0521P-N_v2002" geometry={nodes['MSRC-RCLAMP0521P-N_v2002'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2002'].material} />
            <mesh name="MSRC-RCLAMP0521P-N_v2002_1" geometry={nodes['MSRC-RCLAMP0521P-N_v2002_1'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2002_1'].material} />
          </group>
        </group>
        <group name="122" userData={{ name: '122' }}>
          <group name="121" position={[-0.0022998785, 0, -0.0065000826]} rotation={[-Math.PI, -8.74e-8, -Math.PI]} userData={{ name: '121' }}>
            <mesh name="MSRC-RCLAMP0521P-N_v2003" geometry={nodes['MSRC-RCLAMP0521P-N_v2003'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2003'].material} />
            <mesh name="MSRC-RCLAMP0521P-N_v2003_1" geometry={nodes['MSRC-RCLAMP0521P-N_v2003_1'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2003_1'].material} />
          </group>
        </group>
        <group name="124" userData={{ name: '124' }}>
          <group name="123" position={[-0.0024227728, 0, -0.0044499994]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '123' }}>
            <mesh name="MSRC-Nexperia_SOT23" geometry={nodes['MSRC-Nexperia_SOT23'].geometry} material={materials.mat_19} />
            <mesh name="MSRC-Nexperia_SOT23_1" geometry={nodes['MSRC-Nexperia_SOT23_1'].geometry} material={nodes['MSRC-Nexperia_SOT23_1'].material} />
            <mesh name="MSRC-Nexperia_SOT23_2" geometry={nodes['MSRC-Nexperia_SOT23_2'].geometry} material={nodes['MSRC-Nexperia_SOT23_2'].material} />
          </group>
        </group>
        <group name="130" userData={{ name: '130' }}>
          <group name="126" position={[0.0046999995, 0, 0.0041500013]} userData={{ name: '126' }}>
            <mesh name="1" geometry={nodes['1'].geometry} material={nodes['1'].material} userData={{ name: '1' }} />
          </group>
          <group name="128" position={[0.0046999231, 0, 0.0048349206]} userData={{ name: '128' }}>
            <mesh name="2" geometry={nodes['2'].geometry} material={nodes['2'].material} userData={{ name: '2' }} />
          </group>
          <group name="129" position={[0.0047000758, 0, 0.0034650837]} userData={{ name: '129' }}>
            <mesh name="2001" geometry={nodes['2001'].geometry} material={nodes['2001'].material} userData={{ name: '2.001' }} />
          </group>
        </group>
        <group name="136" userData={{ name: '136' }}>
          <group name="132" position={[-0.0051150792, 0, -0.0028499188]} userData={{ name: '132' }}>
            <mesh name="3" geometry={nodes['3'].geometry} material={nodes['3'].material} userData={{ name: '3' }} />
          </group>
          <group name="133" position={[-0.006484922, 0, -0.002850079]} userData={{ name: '133' }}>
            <mesh name="3001" geometry={nodes['3001'].geometry} material={nodes['3001'].material} userData={{ name: '3.001' }} />
          </group>
          <group name="135" position={[-0.0058000004, 0, -0.002849997]} userData={{ name: '135' }}>
            <mesh name="4" geometry={nodes['4'].geometry} material={nodes['4'].material} userData={{ name: '4' }} />
          </group>
        </group>
        <group name="140" userData={{ name: '140' }}>
          <group name="137" position={[-0.0004999213, 0, 0.0035650821]} userData={{ name: '137' }}>
            <mesh name="2002" geometry={nodes['2002'].geometry} material={nodes['2002'].material} userData={{ name: '2.002' }} />
          </group>
          <group name="138" position={[-0.0005000891, 0, 0.0049349209]} userData={{ name: '138' }}>
            <mesh name="2003" geometry={nodes['2003'].geometry} material={nodes['2003'].material} userData={{ name: '2.003' }} />
          </group>
          <group name="139" position={[-0.0004999975, 0, 0.0042500016]} userData={{ name: '139' }}>
            <mesh name="1001" geometry={nodes['1001'].geometry} material={nodes['1001'].material} userData={{ name: '1.001' }} />
          </group>
        </group>
        <group name="142" userData={{ name: '142' }}>
          <group name="141" position={[0.0016230035, 0, -0.0042249169]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '141' }}>
            <mesh name="CC0603" geometry={nodes.CC0603.geometry} material={nodes.CC0603.material} />
            <mesh name="CC0603_1" geometry={nodes.CC0603_1.geometry} material={nodes.CC0603_1.material} />
          </group>
        </group>
        <group name="74" userData={{ name: '74' }}>
          <group name="73" position={[0, -0.0015454402, 0]} userData={{ name: '73' }}>
            <mesh name="72" geometry={nodes['72'].geometry} material={materials.mat_0} userData={{ name: '72' }} />
          </group>
        </group>
        <group name="86" userData={{ name: '86' }}>
          <group name="79" position={[0.0074000419, 0.0025399986, 0.0076551111]} rotation={[Math.PI / 2, -2.98e-8, -Math.PI / 2]} userData={{ name: '79' }}>
            <mesh name="M20-999-MOULD" geometry={nodes['M20-999-MOULD'].geometry} material={nodes['M20-999-MOULD'].material} userData={{ name: 'M20-999-MOULD' }} />
            <mesh name="M20-999-PIN" geometry={nodes['M20-999-PIN'].geometry} material={nodes['M20-999-PIN'].material} position={[0.00254, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN' }} />
            <mesh name="M20-999-PIN001" geometry={nodes['M20-999-PIN001'].geometry} material={nodes['M20-999-PIN001'].material} position={[0.00508, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.001' }} />
            <mesh name="M20-999-PIN002" geometry={nodes['M20-999-PIN002'].geometry} material={nodes['M20-999-PIN002'].material} position={[0.0076199998, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.002' }} />
          </group>
          <group name="83" position={[0.007400088, 0.0025499985, 0.0000350529]} rotation={[Math.PI / 2, -2.98e-8, -Math.PI / 2]} userData={{ name: '83' }}>
            <mesh name="M20-999-MOULD001" geometry={nodes['M20-999-MOULD001'].geometry} material={nodes['M20-999-MOULD001'].material} userData={{ name: 'M20-999-MOULD.001' }} />
            <mesh name="M20-999-PIN003" geometry={nodes['M20-999-PIN003'].geometry} material={nodes['M20-999-PIN003'].material} position={[0.00254, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.003' }} />
            <mesh name="M20-999-PIN004" geometry={nodes['M20-999-PIN004'].geometry} material={nodes['M20-999-PIN004'].material} position={[0.00508, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.004' }} />
          </group>
          <group name="84" position={[0.0099400505, 0.0025399986, 0.0076551111]} rotation={[Math.PI / 2, -2.98e-8, -Math.PI / 2]} userData={{ name: '84' }}>
            <mesh name="M20-999-MOULD002" geometry={nodes['M20-999-MOULD002'].geometry} material={nodes['M20-999-MOULD002'].material} userData={{ name: 'M20-999-MOULD.002' }} />
            <mesh name="M20-999-PIN005" geometry={nodes['M20-999-PIN005'].geometry} material={nodes['M20-999-PIN005'].material} position={[0.00254, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.005' }} />
            <mesh name="M20-999-PIN006" geometry={nodes['M20-999-PIN006'].geometry} material={nodes['M20-999-PIN006'].material} position={[0.00508, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.006' }} />
            <mesh name="M20-999-PIN007" geometry={nodes['M20-999-PIN007'].geometry} material={nodes['M20-999-PIN007'].material} position={[0.0076199998, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.007' }} />
          </group>
          <group name="85" position={[0.0099400962, 0.0025499985, 0.0000350529]} rotation={[Math.PI / 2, -2.98e-8, -Math.PI / 2]} userData={{ name: '85' }}>
            <mesh name="M20-999-MOULD003" geometry={nodes['M20-999-MOULD003'].geometry} material={nodes['M20-999-MOULD003'].material} userData={{ name: 'M20-999-MOULD.003' }} />
            <mesh name="M20-999-PIN008" geometry={nodes['M20-999-PIN008'].geometry} material={nodes['M20-999-PIN008'].material} position={[0.00254, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.008' }} />
            <mesh name="M20-999-PIN009" geometry={nodes['M20-999-PIN009'].geometry} material={nodes['M20-999-PIN009'].material} position={[0.00508, 0, 0.0055800001]} rotation={[-Math.PI, 0, 0]} userData={{ name: 'M20-999-PIN.009' }} />
          </group>
        </group>
        <group name="88" userData={{ name: '88' }}>
          <group name="87" position={[-0.0022001166, 0, 0.001099878]} rotation={[0, Math.PI / 2, 0]} userData={{ name: '87' }}>
            <mesh name="RC0603N" geometry={nodes.RC0603N.geometry} material={nodes.RC0603N.material} />
            <mesh name="RC0603N_1" geometry={nodes.RC0603N_1.geometry} material={nodes.RC0603N_1.material} />
          </group>
        </group>
        <group name="90" userData={{ name: '90' }}>
          <group name="89" position={[0.0000254236, 0, -0.0020001223]} userData={{ name: '89' }}>
            <mesh name="RC0603N001" geometry={nodes.RC0603N001.geometry} material={nodes.RC0603N001.material} />
            <mesh name="RC0603N001_1" geometry={nodes.RC0603N001_1.geometry} material={nodes.RC0603N001_1.material} />
          </group>
        </group>
        <group name="92" userData={{ name: '92' }}>
          <group name="91" position={[0.0025001245, 0, 0]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '91' }}>
            <mesh name="RC0603N002" geometry={nodes.RC0603N002.geometry} material={nodes.RC0603N002.material} />
            <mesh name="RC0603N002_1" geometry={nodes.RC0603N002_1.geometry} material={nodes.RC0603N002_1.material} />
          </group>
        </group>
        <group name="94" userData={{ name: '94' }}>
          <group name="93" rotation={[0, Math.PI / 2, 0]} userData={{ name: '93' }}>
            <mesh name="MSRC-TZ-P4-1615RGBTCA1-055T" geometry={nodes['MSRC-TZ-P4-1615RGBTCA1-055T'].geometry} material={nodes['MSRC-TZ-P4-1615RGBTCA1-055T'].material} />
            <mesh name="MSRC-TZ-P4-1615RGBTCA1-055T_1" geometry={nodes['MSRC-TZ-P4-1615RGBTCA1-055T_1'].geometry} material={nodes['MSRC-TZ-P4-1615RGBTCA1-055T_1'].material} />
          </group>
        </group>
        <group name="96" userData={{ name: '96' }}>
          <group name="95" position={[-0.0018998694, 0, 0.0042501255]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '95' }}>
            <mesh name="RC0603N003" geometry={nodes.RC0603N003.geometry} material={nodes.RC0603N003.material} />
            <mesh name="RC0603N003_1" geometry={nodes.RC0603N003_1.geometry} material={nodes.RC0603N003_1.material} />
          </group>
        </group>
        <group name="98" userData={{ name: '98' }}>
          <group name="97" position={[0, 0, 0.0065500829]} userData={{ name: '97' }}>
            <mesh name="MSRC-0603_LED_Orange" geometry={nodes['MSRC-0603_LED_Orange'].geometry} material={nodes['MSRC-0603_LED_Orange'].material} />
            <mesh name="MSRC-0603_LED_Orange_1" geometry={nodes['MSRC-0603_LED_Orange_1'].geometry} material={nodes['MSRC-0603_LED_Orange_1'].material} />
            <mesh name="MSRC-0603_LED_Orange_2" geometry={nodes['MSRC-0603_LED_Orange_2'].geometry} material={nodes['MSRC-0603_LED_Orange_2'].material} />
            <mesh name="MSRC-0603_LED_Orange_3" geometry={nodes['MSRC-0603_LED_Orange_3'].geometry} material={nodes['MSRC-0603_LED_Orange_3'].material} />
            <mesh name="MSRC-0603_LED_Orange_4" geometry={nodes['MSRC-0603_LED_Orange_4'].geometry} material={nodes['MSRC-0603_LED_Orange_4'].material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Jacdac_RGBLED.gltf')
