/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Jacdac_RotaryModule.gltf')
  // eslint-disable-next-line react/prop-types
  

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="PCB"
        scale={1000}
        userData={{
          name: 'PCB',
          userData: {
            JD_PWR: [{ x: 5, y: -10 }],
            JD_DATA: [{ x: -5, y: -10 }],
            JD_GND: [
              { x: -5, y: 10 },
              { x: 5, y: 10 },
            ],
          },
        }}>
        
        <group name="JD_PWR"  position={[0.005, 0, -0.010]}>

        </group>
        <group name="JD_DATA"  position={[-0.005, 0, -0.010]}>

        </group>
        <group name="JD_GND1" position={[-0.005, 0, 0.010]}></group>
        <group name="JD_GND2" position={[0.005, 0, 0.010]}></group>
        <group name="15" userData={{ name: '15' }}>
          <group name="11" position={[0.0024526545, 0, -0.0046248403]} userData={{ name: '11' }}>
            <mesh name="2001" geometry={nodes['2001'].geometry} material={nodes['2001'].material} userData={{ name: '2.001' }} />
          </group>
          <group name="12" position={[0.0024526545, 0, -0.0038748404]} userData={{ name: '12' }}>
            <mesh name="2002" geometry={nodes['2002'].geometry} material={nodes['2002'].material} userData={{ name: '2.002' }} />
          </group>
          <group name="14" position={[0.0024526392, 0, -0.0042498517]} userData={{ name: '14' }}>
            <mesh name="1001" geometry={nodes['1001'].geometry} material={nodes['1001'].material} userData={{ name: '1.001' }} />
          </group>
        </group>
        <group name="2" userData={{ name: '2' }}>
          <mesh name="1" geometry={nodes['1'].geometry} material={materials.mat_0} position={[0, -0.0015454402, 0]} userData={{ name: '1' }} />
        </group>
        <group name="20" userData={{ name: '20' }}>
          <group name="17" position={[0.0047967858, 0, -0.0042500007]} userData={{ name: '17' }}>
            <mesh name="9001" geometry={nodes['9001'].geometry} material={nodes['9001'].material} userData={{ name: '9.001' }} />
          </group>
          <group name="18" position={[0.0040467861, 0, -0.0042500007]} userData={{ name: '18' }}>
            <mesh name="9002" geometry={nodes['9002'].geometry} material={nodes['9002'].material} userData={{ name: '9.002' }} />
          </group>
          <group name="19" position={[0.0044218013, 0, -0.0042500119]} userData={{ name: '19' }}>
            <mesh name="1002" geometry={nodes['1002'].geometry} material={nodes['1002'].material} userData={{ name: '1.002' }} />
          </group>
        </group>
        <group name="24" userData={{ name: '24' }}>
          <group name="21" position={[0.0043000057, 0, -0.0056499983]} userData={{ name: '21' }}>
            <mesh name="9003" geometry={nodes['9003'].geometry} material={nodes['9003'].material} userData={{ name: '9.003' }} />
          </group>
          <group name="22" position={[0.0035500056, 0, -0.0056499983]} userData={{ name: '22' }}>
            <mesh name="9004" geometry={nodes['9004'].geometry} material={nodes['9004'].material} userData={{ name: '9.004' }} />
          </group>
          <group name="23" position={[0.0039250054, 0, -0.0056500095]} userData={{ name: '23' }}>
            <mesh name="1003" geometry={nodes['1003'].geometry} material={nodes['1003'].material} userData={{ name: '1.003' }} />
          </group>
        </group>
        <group name="28" userData={{ name: '28' }}>
          <group name="25" position={[0.0005249964, 0, -0.005650002]} userData={{ name: '25' }}>
            <mesh name="9005" geometry={nodes['9005'].geometry} material={nodes['9005'].material} userData={{ name: '9.005' }} />
          </group>
          <group name="26" position={[0.0012749963, 0, -0.005650002]} userData={{ name: '26' }}>
            <mesh name="9006" geometry={nodes['9006'].geometry} material={nodes['9006'].material} userData={{ name: '9.006' }} />
          </group>
          <group name="27" position={[0.0008999811, 0, -0.0056499867]} userData={{ name: '27' }}>
            <mesh name="1004" geometry={nodes['1004'].geometry} material={nodes['1004'].material} userData={{ name: '1.004' }} />
          </group>
        </group>
        <group name="32" userData={{ name: '32' }}>
          <group name="29" position={[-0.004014127, 0, 0.0049751848]} userData={{ name: '29' }}>
            <mesh name="2003" geometry={nodes['2003'].geometry} material={nodes['2003'].material} userData={{ name: '2.003' }} />
          </group>
          <group name="30" position={[-0.004014127, 0, 0.0042251847]} userData={{ name: '30' }}>
            <mesh name="2004" geometry={nodes['2004'].geometry} material={nodes['2004'].material} userData={{ name: '2.004' }} />
          </group>
          <group name="31" position={[-0.004014127, 0, 0.0046001961]} userData={{ name: '31' }}>
            <mesh name="1005" geometry={nodes['1005'].geometry} material={nodes['1005'].material} userData={{ name: '1.005' }} />
          </group>
        </group>
        <group name="38" userData={{ name: '38' }}>
          <group name="34" position={[-0.0040899939, 0, 0.0062749973]} userData={{ name: '34' }}>
            <mesh name="7001" geometry={nodes['7001'].geometry} material={nodes['7001'].material} userData={{ name: '7.001' }} />
          </group>
          <group name="35" position={[-0.005359998, 0, 0.0062749973]} userData={{ name: '35' }}>
            <mesh name="7002" geometry={nodes['7002'].geometry} material={nodes['7002'].material} userData={{ name: '7.002' }} />
          </group>
          <group name="37" position={[-0.0047250036, 0, 0.006275001]} userData={{ name: '37' }}>
            <mesh name="8001" geometry={nodes['8001'].geometry} material={materials.mat_10} userData={{ name: '8.001' }} />
          </group>
        </group>
        <group name="4" userData={{ name: '4' }}>
          <group name="3" position={[0.002086703, 0, 0.0118088759]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: '3' }}>
            <mesh name="MSRC-RCLAMP0521P-N_v2" geometry={nodes['MSRC-RCLAMP0521P-N_v2'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2'].material} />
            <mesh name="MSRC-RCLAMP0521P-N_v2_1" geometry={nodes['MSRC-RCLAMP0521P-N_v2_1'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2_1'].material} />
          </group>
        </group>
        <group name="44" userData={{ name: '44' }}>
          <group name="40" position={[0.0013750024, 0, -0.0043499991]} userData={{ name: '40' }}>
            <mesh name="5" geometry={nodes['5'].geometry} material={nodes['5'].material} userData={{ name: '5' }} />
          </group>
          <group name="42" position={[0.0009749933, 0, -0.0043499954]} userData={{ name: '42' }}>
            <mesh name="6001" geometry={nodes['6001'].geometry} material={nodes['6001'].material} userData={{ name: '6.001' }} />
          </group>
          <group name="43" position={[0.0005749994, 0, -0.0043500792]} userData={{ name: '43' }}>
            <mesh name="5001" geometry={nodes['5001'].geometry} material={nodes['5001'].material} userData={{ name: '5.001' }} />
          </group>
        </group>
        <group name="48" userData={{ name: '48' }}>
          <group name="45" position={[0.0040214714, 0, -0.0030153242]} userData={{ name: '45' }}>
            <mesh name="5002" geometry={nodes['5002'].geometry} material={nodes['5002'].material} userData={{ name: '5.002' }} />
          </group>
          <group name="46" position={[0.0044214809, 0, -0.003015328]} userData={{ name: '46' }}>
            <mesh name="6002" geometry={nodes['6002'].geometry} material={nodes['6002'].material} userData={{ name: '6.002' }} />
          </group>
          <group name="47" position={[0.0048214747, 0, -0.0030152402]} userData={{ name: '47' }}>
            <mesh name="5003" geometry={nodes['5003'].geometry} material={nodes['5003'].material} userData={{ name: '5.003' }} />
          </group>
        </group>
        <group name="54" userData={{ name: '54' }}>
          <group name="50" position={[0.0041701379, 0, 0.0004750017]} userData={{ name: '50' }}>
            <mesh name="3001" geometry={nodes['3001'].geometry} material={nodes['3001'].material} userData={{ name: '3.001' }} />
          </group>
          <group name="52" position={[0.0041700462, 0, 0.0008749994]} userData={{ name: '52' }}>
            <mesh name="4001" geometry={nodes['4001'].geometry} material={nodes['4001'].material} userData={{ name: '4.001' }} />
          </group>
          <group name="53" position={[0.0041700462, 0, 0.0012749971]} userData={{ name: '53' }}>
            <mesh name="3002" geometry={nodes['3002'].geometry} material={nodes['3002'].material} userData={{ name: '3.002' }} />
          </group>
        </group>
        <group name="58" userData={{ name: '58' }}>
          <group name="55" position={[0.0050799889, 0, 0.0069814217]} userData={{ name: '55' }}>
            <mesh name="5004" geometry={nodes['5004'].geometry} material={nodes['5004'].material} userData={{ name: '5.004' }} />
          </group>
          <group name="56" position={[0.0046799951, 0, 0.0069813379]} userData={{ name: '56' }}>
            <mesh name="6003" geometry={nodes['6003'].geometry} material={nodes['6003'].material} userData={{ name: '6.003' }} />
          </group>
          <group name="57" position={[0.004279986, 0, 0.0069813416]} userData={{ name: '57' }}>
            <mesh name="5005" geometry={nodes['5005'].geometry} material={nodes['5005'].material} userData={{ name: '5.005' }} />
          </group>
        </group>
        <group name="63" userData={{ name: '63' }}>
          <group name="62" position={[0, 0.0024000003, 0.0003000788]} rotation={[-Math.PI, -8.74e-8, -Math.PI]} userData={{ name: '62' }}>
            <mesh name="EC11-Base1" geometry={nodes['EC11-Base1'].geometry} material={nodes['EC11-Base1'].material} position={[0, 0.0044999998, 0]} userData={{ name: 'EC11-Base:1' }} />
            <group name="EC11-Housing-THT1" position={[0, 0.0027999999, 0]} userData={{ name: 'EC11-Housing-THT:1' }}>
              <mesh name="EC11-Housing-THT" geometry={nodes['EC11-Housing-THT'].geometry} material={nodes['EC11-Housing-THT'].material} />
              <mesh name="EC11-Housing-THT_1" geometry={nodes['EC11-Housing-THT_1'].geometry} material={nodes['EC11-Housing-THT_1'].material} />
            </group>
            <mesh name="EC11-Shaft-F1" geometry={nodes['EC11-Shaft-F1'].geometry} material={nodes['EC11-Shaft-F1'].material} position={[0, 0.0044999998, 0]} userData={{ name: 'EC11-Shaft-F:1' }} />
          </group>
        </group>
        <group name="67" userData={{ name: '67' }}>
          <group name="64" position={[-0.0008000159, 0, 0.0083499905]} userData={{ name: '64' }}>
            <mesh name="1006" geometry={nodes['1006'].geometry} material={nodes['1006'].material} userData={{ name: '1.006' }} />
          </group>
          <group name="65" position={[-0.0008000006, 0, 0.0087250015]} userData={{ name: '65' }}>
            <mesh name="2005" geometry={nodes['2005'].geometry} material={nodes['2005'].material} userData={{ name: '2.005' }} />
          </group>
          <group name="66" position={[-0.0008000006, 0, 0.0079750018]} userData={{ name: '66' }}>
            <mesh name="2006" geometry={nodes['2006'].geometry} material={nodes['2006'].material} userData={{ name: '2.006' }} />
          </group>
        </group>
        <group name="7" userData={{ name: '7' }}>
          <group name="6" position={[0.0050998712, 0, 0.0042249598]} rotation={[0, Math.PI / 2, 0]} userData={{ name: '6' }}>
            <group name="Model1" userData={{ name: 'Model:1' }}>
              <mesh name="Model" geometry={nodes.Model.geometry} material={materials.mat_3} />
              <mesh name="Model_1" geometry={nodes.Model_1.geometry} material={materials.mat_4} />
            </group>
          </group>
        </group>
        <group name="71" userData={{ name: '71' }}>
          <group name="68" position={[0.0004499994, 0, 0.0079750018]} userData={{ name: '68' }}>
            <mesh name="2007" geometry={nodes['2007'].geometry} material={nodes['2007'].material} userData={{ name: '2.007' }} />
          </group>
          <group name="69" position={[0.0004499994, 0, 0.0087250015]} userData={{ name: '69' }}>
            <mesh name="2008" geometry={nodes['2008'].geometry} material={nodes['2008'].material} userData={{ name: '2.008' }} />
          </group>
          <group name="70" position={[0.0004499841, 0, 0.0083499905]} userData={{ name: '70' }}>
            <mesh name="1007" geometry={nodes['1007'].geometry} material={nodes['1007'].material} userData={{ name: '1.007' }} />
          </group>
        </group>
        <group name="73" userData={{ name: '73' }}>
          <mesh name="72" geometry={nodes['72'].geometry} material={materials.mat_14} position={[-0.000245954, 0, 0.0105249593]} rotation={[0, Math.PI / 2, 0]} userData={{ name: '72' }} />
        </group>
        <group name="75" userData={{ name: '75' }}>
          <group name="74" position={[0, 0, 0.0011499552]} rotation={[0, Math.PI / 2, 0]} userData={{ name: '74' }}>
            <mesh name="TSSOP20_STM" geometry={nodes.TSSOP20_STM.geometry} material={materials.mat_15} />
            <mesh name="TSSOP20_STM_1" geometry={nodes.TSSOP20_STM_1.geometry} material={materials.mat_16} />
            <mesh name="TSSOP20_STM_2" geometry={nodes.TSSOP20_STM_2.geometry} material={materials.mat_17} />
          </group>
        </group>
        <group name="79" userData={{ name: '79' }}>
          <group name="76" position={[0.0016749903, 0, 0.0099499887]} userData={{ name: '76' }}>
            <mesh name="1008" geometry={nodes['1008'].geometry} material={nodes['1008'].material} userData={{ name: '1.008' }} />
          </group>
          <group name="77" position={[0.0016750055, 0, 0.0103250006]} userData={{ name: '77' }}>
            <mesh name="2009" geometry={nodes['2009'].geometry} material={nodes['2009'].material} userData={{ name: '2.009' }} />
          </group>
          <group name="78" position={[0.0016750055, 0, 0.0095750038]} userData={{ name: '78' }}>
            <mesh name="2010" geometry={nodes['2010'].geometry} material={nodes['2010'].material} userData={{ name: '2.010' }} />
          </group>
        </group>
        <group name="81" userData={{ name: '81' }}>
          <group name="80" position={[-0.0017498755, 0, 0.0120749203]} rotation={[-Math.PI, -8.74e-8, -Math.PI]} userData={{ name: '80' }}>
            <mesh name="MSRC-RCLAMP0521P-N_v2001" geometry={nodes['MSRC-RCLAMP0521P-N_v2001'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2001'].material} />
            <mesh name="MSRC-RCLAMP0521P-N_v2001_1" geometry={nodes['MSRC-RCLAMP0521P-N_v2001_1'].geometry} material={nodes['MSRC-RCLAMP0521P-N_v2001_1'].material} />
          </group>
        </group>
        <group name="85" userData={{ name: '85' }}>
          <group name="82" position={[-0.0003947577, 0, -0.0032300763]} userData={{ name: '82' }}>
            <mesh name="5006" geometry={nodes['5006'].geometry} material={nodes['5006'].material} userData={{ name: '5.006' }} />
          </group>
          <group name="83" position={[0.0000052362, 0, -0.003230084]} userData={{ name: '83' }}>
            <mesh name="6004" geometry={nodes['6004'].geometry} material={nodes['6004'].material} userData={{ name: '6.004' }} />
          </group>
          <group name="84" position={[0.0004052301, 0, -0.0032299962]} userData={{ name: '84' }}>
            <mesh name="5007" geometry={nodes['5007'].geometry} material={nodes['5007'].material} userData={{ name: '5.007' }} />
          </group>
        </group>
        <group name="89" userData={{ name: '89' }}>
          <group name="86" position={[-0.0027499977, 0, 0.0056749987]} userData={{ name: '86' }}>
            <mesh name="5008" geometry={nodes['5008'].geometry} material={nodes['5008'].material} userData={{ name: '5.008' }} />
          </group>
          <group name="87" position={[-0.0023500037, 0, 0.005674995]} userData={{ name: '87' }}>
            <mesh name="6005" geometry={nodes['6005'].geometry} material={nodes['6005'].material} userData={{ name: '6.005' }} />
          </group>
          <group name="88" position={[-0.0019499945, 0, 0.0056750826]} userData={{ name: '88' }}>
            <mesh name="5009" geometry={nodes['5009'].geometry} material={nodes['5009'].material} userData={{ name: '5.009' }} />
          </group>
        </group>
        <group name="9" userData={{ name: '9' }}>
          <group name="8" position={[-0.0062280251, 0, 0.0037769962]} rotation={[-Math.PI, -8.74e-8, -Math.PI]} userData={{ name: '8' }}>
            <mesh name="MSRC-Nexperia_SOT23" geometry={nodes['MSRC-Nexperia_SOT23'].geometry} material={materials.mat_5} />
            <mesh name="MSRC-Nexperia_SOT23_1" geometry={nodes['MSRC-Nexperia_SOT23_1'].geometry} material={materials.mat_6} />
            <mesh name="MSRC-Nexperia_SOT23_2" geometry={nodes['MSRC-Nexperia_SOT23_2'].geometry} material={materials.mat_7} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Jacdac_RotaryModule.gltf')
