/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/jacdac_rgbledring.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={1000}>
      <mesh name="jacdac_rgbledring" geometry={nodes.jacdac_rgbledring.geometry} material={materials.mat_14} userData={{ name: 'jacdac_rgbledring' }}>
      
      <group name="JD_PWR"  position={[-0.011370, 0, 0.01500]}></group>
      <group name="JD_DATA"  position={[-0.011370, 0, -0.01500]}></group>
      <group name="JD_GND1" position={[0.01863, 0, -0.01500]}></group>
      <group name="JD_GND2" position={[0.01863, 0, 0.01500]}></group>
      
        <group name="11" position={[-0.0076516494, 0.0008499906, 0.0055693984]} rotation={[0, 1.5705346837, 0]} userData={{ name: '11' }}>
          <group name="=>0117" userData={{ name: '=>[0:1:1:7]' }}>
            <mesh name="SOLID007" geometry={nodes.SOLID007.geometry} material={materials.mat_4} />
            <mesh name="SOLID007_1" geometry={nodes.SOLID007_1.geometry} material={materials.mat_5} />
          </group>
        </group>
        <group name="12" position={[0.0172941536, 0.0008499906, 0.0061589926]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} userData={{ name: '12' }}>
          <group name="=>0115003" userData={{ name: '=>[0:1:1:5].003' }}>
            <mesh name="SOLID008" geometry={nodes.SOLID008.geometry} material={materials.mat_2} />
            <mesh name="SOLID008_1" geometry={nodes.SOLID008_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="13" position={[-0.0023693517, 0.0008499906, 0.0089871958]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} userData={{ name: '13' }}>
          <group name="=>0113004" userData={{ name: '=>[0:1:1:3].004' }}>
            <mesh name="SOLID009" geometry={nodes.SOLID009.geometry} material={materials.mat_0} />
            <mesh name="SOLID009_1" geometry={nodes.SOLID009_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID009_2" geometry={nodes.SOLID009_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="14" position={[0.0060484484, 0.0008499906, 0.0124943927]} rotation={[-Math.PI, 0, -Math.PI]} userData={{ name: '14' }}>
          <group name="=>0113005" userData={{ name: '=>[0:1:1:3].005' }}>
            <mesh name="SOLID010" geometry={nodes.SOLID010.geometry} material={materials.mat_0} />
            <mesh name="SOLID010_1" geometry={nodes.SOLID010_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID010_2" geometry={nodes.SOLID010_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="15" position={[-0.0076516494, 0.0008499906, -0.004430607]} rotation={[0, -1.5705346837, 0]} userData={{ name: '15' }}>
          <group name="=>0117001" userData={{ name: '=>[0:1:1:7].001' }}>
            <mesh name="SOLID011" geometry={nodes.SOLID011.geometry} material={materials.mat_4} />
            <mesh name="SOLID011_1" geometry={nodes.SOLID011_1.geometry} material={materials.mat_5} />
          </group>
        </group>
        <group name="16" position={[0.0060482472, 0.0008499906, -0.0113557056]} userData={{ name: '16' }}>
          <group name="=>0113006" userData={{ name: '=>[0:1:1:3].006' }}>
            <mesh name="SOLID012" geometry={nodes.SOLID012.geometry} material={materials.mat_0} />
            <mesh name="SOLID012_1" geometry={nodes.SOLID012_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID012_2" geometry={nodes.SOLID012_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="17" position={[0.0179733485, 0.0008499906, -0.0034307018]} rotation={[-Math.PI, 0, -Math.PI]} userData={{ name: '17' }}>
          <group name="=>0115004" userData={{ name: '=>[0:1:1:5].004' }}>
            <mesh name="SOLID013" geometry={nodes.SOLID013.geometry} material={materials.mat_2} />
            <mesh name="SOLID013_1" geometry={nodes.SOLID013_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="18" position={[0.0020482466, 0.0008499906, -0.0113557056]} rotation={[0, -1.5705346837, 0]} userData={{ name: '18' }}>
          <group name="=>0115005" userData={{ name: '=>[0:1:1:5].005' }}>
            <mesh name="SOLID014" geometry={nodes.SOLID014.geometry} material={materials.mat_2} />
            <mesh name="SOLID014_1" geometry={nodes.SOLID014_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="19" position={[0.0179733485, 0.0008499906, 0.0005692989]} rotation={[0, -1.5705346837, 0]} userData={{ name: '19' }}>
          <group name="=>0113007" userData={{ name: '=>[0:1:1:3].007' }}>
            <mesh name="SOLID015" geometry={nodes.SOLID015.geometry} material={materials.mat_0} />
            <mesh name="SOLID015_1" geometry={nodes.SOLID015_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID015_2" geometry={nodes.SOLID015_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="2" position={[0.0144659504, 0.0008499906, -0.0078484043]} rotation={[0, -Math.PI / 4, 0]} userData={{ name: '2' }}>
          <group name="=>0113" userData={{ name: '=>[0:1:1:3]' }}>
            <mesh name="SOLID" geometry={nodes.SOLID.geometry} material={materials.mat_0} />
            <mesh name="SOLID_1" geometry={nodes.SOLID_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID_2" geometry={nodes.SOLID_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="20" position={[0.0004586503, 0.0008499906, 0.0118151978]} rotation={[0, Math.PI / 4, 0]} userData={{ name: '20' }}>
          <group name="=>0115006" userData={{ name: '=>[0:1:1:5].006' }}>
            <mesh name="SOLID016" geometry={nodes.SOLID016.geometry} material={materials.mat_2} />
            <mesh name="SOLID016_1" geometry={nodes.SOLID016_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="21" position={[-0.0051974505, 0.0008499906, -0.0050203055]} rotation={[0, -Math.PI / 4, 0]} userData={{ name: '21' }}>
          <group name="=>0115007" userData={{ name: '=>[0:1:1:5].007' }}>
            <mesh name="SOLID017" geometry={nodes.SOLID017.geometry} material={materials.mat_2} />
            <mesh name="SOLID017_1" geometry={nodes.SOLID017_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="23" position={[-0.0023694485, -0.0008500093, -0.0078483075]} rotation={[0, Math.PI / 4, Math.PI]} userData={{ name: '23' }}>
          <group name="=>0119" userData={{ name: '=>[0:1:1:9]' }}>
            <mesh name="SOLID018" geometry={nodes.SOLID018.geometry} material={materials.mat_6} />
            <mesh name="SOLID018_1" geometry={nodes.SOLID018_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID018_2" geometry={nodes.SOLID018_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="25" position={[-0.0099516511, -0.0008500093, -0.0083106011]} rotation={[Math.PI, Math.PI / 4, 0]} userData={{ name: '25' }}>
          <group name="=>01111" userData={{ name: '=>[0:1:1:11]' }}>
            <mesh name="SOLID019" geometry={nodes.SOLID019.geometry} material={materials.mat_7} />
            <mesh name="SOLID019_1" geometry={nodes.SOLID019_1.geometry} material={materials.mat_6} />
          </group>
        </group>
        <group name="26" position={[-0.0056716502, -0.0008500093, -0.0025306046]} rotation={[Math.PI, Math.PI / 2, 0]} userData={{ name: '26' }}>
          <group name="=>0115008" userData={{ name: '=>[0:1:1:5].008' }}>
            <mesh name="SOLID020" geometry={nodes.SOLID020.geometry} material={materials.mat_2} />
            <mesh name="SOLID020_1" geometry={nodes.SOLID020_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="28" position={[-0.007746987, -0.0008500093, -0.0092694461]} rotation={[Math.PI, Math.PI / 4, 0]} userData={{ name: '28' }}>
          <group name="=>01113" userData={{ name: '=>[0:1:1:13]' }}>
            <mesh name="SOLID021" geometry={nodes.SOLID021.geometry} material={materials.mat_2} />
            <mesh name="SOLID021_1" geometry={nodes.SOLID021_1.geometry} material={materials.mat_9} />
            <mesh name="SOLID021_2" geometry={nodes.SOLID021_2.geometry} material={materials.mat_10} />
          </group>
        </group>
        <group name="29" position={[-0.004691653, -0.0008500093, -0.0025306046]} rotation={[Math.PI, -Math.PI / 2, 0]} userData={{ name: '29' }}>
          <group name="=>01113001" userData={{ name: '=>[0:1:1:13].001' }}>
            <mesh name="SOLID022" geometry={nodes.SOLID022.geometry} material={materials.mat_2} />
            <mesh name="SOLID022_1" geometry={nodes.SOLID022_1.geometry} material={materials.mat_9} />
            <mesh name="SOLID022_2" geometry={nodes.SOLID022_2.geometry} material={materials.mat_10} />
          </group>
        </group>
        <group name="30" position={[-0.0048767477, -0.0008500093, 0.0005694926]} rotation={[Math.PI, -Math.PI / 2, 0]} userData={{ name: '30' }}>
          <group name="=>01111001" userData={{ name: '=>[0:1:1:11].001' }}>
            <mesh name="SOLID023" geometry={nodes.SOLID023.geometry} material={materials.mat_7} />
            <mesh name="SOLID023_1" geometry={nodes.SOLID023_1.geometry} material={materials.mat_6} />
          </group>
        </group>
        <group name="31" position={[-0.0076416507, -0.0008500093, -0.0025306046]} rotation={[Math.PI, Math.PI / 2, 0]} userData={{ name: '31' }}>
          <group name="=>01113002" userData={{ name: '=>[0:1:1:13].002' }}>
            <mesh name="SOLID024" geometry={nodes.SOLID024.geometry} material={materials.mat_2} />
            <mesh name="SOLID024_1" geometry={nodes.SOLID024_1.geometry} material={materials.mat_9} />
            <mesh name="SOLID024_2" geometry={nodes.SOLID024_2.geometry} material={materials.mat_10} />
          </group>
        </group>
        <group name="32" position={[-0.006836988, -0.0008500093, -0.0113794431]} rotation={[Math.PI, Math.PI / 4, 0]} userData={{ name: '32' }}>
          <group name="=>01111002" userData={{ name: '=>[0:1:1:11].002' }}>
            <mesh name="SOLID025" geometry={nodes.SOLID025.geometry} material={materials.mat_7} />
            <mesh name="SOLID025_1" geometry={nodes.SOLID025_1.geometry} material={materials.mat_6} />
          </group>
        </group>
        <group name="33" position={[-0.0061069876, -0.0008500093, -0.0135294423]} rotation={[0, -Math.PI / 4, -Math.PI]} userData={{ name: '33' }}>
          <group name="=>0115009" userData={{ name: '=>[0:1:1:5].009' }}>
            <mesh name="SOLID026" geometry={nodes.SOLID026.geometry} material={materials.mat_2} />
            <mesh name="SOLID026_1" geometry={nodes.SOLID026_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="35" position={[-0.0066616535, -0.0008500093, -0.0025306046]} rotation={[Math.PI, -Math.PI / 2, 0]} userData={{ name: '35' }}>
          <group name="=>01115" userData={{ name: '=>[0:1:1:15]' }}>
            <mesh name="SOLID027" geometry={nodes.SOLID027.geometry} material={materials.mat_2} />
            <mesh name="SOLID027_1" geometry={nodes.SOLID027_1.geometry} material={materials.mat_11} />
          </group>
        </group>
        <group name="36" position={[-0.0121916533, -0.0008500093, -0.0074806064]} rotation={[Math.PI, Math.PI / 4, 0]} userData={{ name: '36' }}>
          <group name="=>01113003" userData={{ name: '=>[0:1:1:13].003' }}>
            <mesh name="SOLID028" geometry={nodes.SOLID028.geometry} material={materials.mat_2} />
            <mesh name="SOLID028_1" geometry={nodes.SOLID028_1.geometry} material={materials.mat_9} />
            <mesh name="SOLID028_2" geometry={nodes.SOLID028_2.geometry} material={materials.mat_10} />
          </group>
        </group>
        <group name="37" position={[-0.0090569854, -0.0008500093, -0.0105894431]} rotation={[0, -Math.PI / 4, -Math.PI]} userData={{ name: '37' }}>
          <group name="=>0115010" userData={{ name: '=>[0:1:1:5].010' }}>
            <mesh name="SOLID029" geometry={nodes.SOLID029.geometry} material={materials.mat_2} />
            <mesh name="SOLID029_1" geometry={nodes.SOLID029_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="39" position={[-0.0076516494, -0.0008500093, 0.0005493984]} rotation={[Math.PI, -Math.PI / 2, 0]} userData={{ name: '39' }}>
          <group name="=>01117" userData={{ name: '=>[0:1:1:17]' }}>
            <mesh name="SOLID030" geometry={nodes.SOLID030.geometry} material={materials.mat_9} />
            <mesh name="SOLID030_1" geometry={nodes.SOLID030_1.geometry} material={materials.mat_12} />
            <mesh name="SOLID030_2" geometry={nodes.SOLID030_2.geometry} material={materials.mat_13} />
          </group>
        </group>
        <group name="4" position={[0.010048449, 0.0008499906, 0.0124943927]} rotation={[0, 1.5705346837, 0]} userData={{ name: '4' }}>
          <group name="=>0115" userData={{ name: '=>[0:1:1:5]' }}>
            <mesh name="SOLID001" geometry={nodes.SOLID001.geometry} material={materials.mat_2} />
            <mesh name="SOLID001_1" geometry={nodes.SOLID001_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="40" position={[-0.0002616495, -0.0008500093, -0.0116306022]} rotation={[Math.PI, Math.PI / 4, 0]} userData={{ name: '40' }}>
          <group name="=>0115011" userData={{ name: '=>[0:1:1:5].011' }}>
            <mesh name="SOLID031" geometry={nodes.SOLID031.geometry} material={materials.mat_2} />
            <mesh name="SOLID031_1" geometry={nodes.SOLID031_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="5" position={[0.0144661516, 0.0008499906, 0.0089869946]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} userData={{ name: '5' }}>
          <group name="=>0113001" userData={{ name: '=>[0:1:1:3].001' }}>
            <mesh name="SOLID002" geometry={nodes.SOLID002.geometry} material={materials.mat_0} />
            <mesh name="SOLID002_1" geometry={nodes.SOLID002_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID002_2" geometry={nodes.SOLID002_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="6" position={[-0.0058767498, 0.0008499906, 0.0005694926]} rotation={[0, 1.5705346837, 0]} userData={{ name: '6' }}>
          <group name="=>0113002" userData={{ name: '=>[0:1:1:3].002' }}>
            <mesh name="SOLID003" geometry={nodes.SOLID003.geometry} material={materials.mat_0} />
            <mesh name="SOLID003_1" geometry={nodes.SOLID003_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID003_2" geometry={nodes.SOLID003_2.geometry} material={materials.mat_2} />
          </group>
        </group>
        <group name="7" position={[0.0116379485, 0.0008499906, -0.0106764063]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} userData={{ name: '7' }}>
          <group name="=>0115001" userData={{ name: '=>[0:1:1:5].001' }}>
            <mesh name="SOLID004" geometry={nodes.SOLID004.geometry} material={materials.mat_2} />
            <mesh name="SOLID004_1" geometry={nodes.SOLID004_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="8" position={[-0.0058767498, 0.0008499906, 0.0045694932]} userData={{ name: '8' }}>
          <group name="=>0115002" userData={{ name: '=>[0:1:1:5].002' }}>
            <mesh name="SOLID005" geometry={nodes.SOLID005.geometry} material={materials.mat_2} />
            <mesh name="SOLID005_1" geometry={nodes.SOLID005_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="9" position={[-0.0023694485, 0.0008499906, -0.0078483075]} rotation={[0, Math.PI / 4, 0]} userData={{ name: '9' }}>
          <group name="=>0113003" userData={{ name: '=>[0:1:1:3].003' }}>
            <mesh name="SOLID006" geometry={nodes.SOLID006.geometry} material={materials.mat_0} />
            <mesh name="SOLID006_1" geometry={nodes.SOLID006_1.geometry} material={materials.mat_1} />
            <mesh name="SOLID006_2" geometry={nodes.SOLID006_2.geometry} material={materials.mat_2} />
          </group>
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/jacdac_rgbledring.gltf')
