/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Jacdac_RotaryModule.gltf')
  return (
    <group ref={group} {...props} scale={1000} dispose={null}>
      <mesh name="jacdac-rotary" geometry={nodes['jacdac-rotary'].geometry} material={materials.mat_14} userData={{ name: 'jacdac-rotary' }}>
        <group name="11" position={[0.0106919408, 0.00085, -0.0047444552]} rotation={[-Math.PI, 0, -Math.PI]} userData={{ name: '11' }}>
          <group name="=>0119" userData={{ name: '=>[0:1:1:9]' }}>
            <mesh name="SOLID006" geometry={nodes.SOLID006.geometry} material={materials.mat_0} />
            <mesh name="SOLID006_1" geometry={nodes.SOLID006_1.geometry} material={materials.mat_6} />
          </group>
        </group>
        <group name="12" position={[-0.0069390684, 0.00085, -0.0082480609]} rotation={[0, 1.5705346837, 0]} userData={{ name: '12' }}>
          <group name="=>0115001" userData={{ name: '=>[0:1:1:5].001' }}>
            <mesh name="SOLID007" geometry={nodes.SOLID007.geometry} material={materials.mat_2} />
            <mesh name="SOLID007_1" geometry={nodes.SOLID007_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="14" position={[0.0106919408, 0.00085, -0.0057356581]} userData={{ name: '14' }}>
          <group name="=>01111" userData={{ name: '=>[0:1:1:11]' }}>
            <mesh name="SOLID008" geometry={nodes.SOLID008.geometry} material={materials.mat_0} />
            <mesh name="SOLID008_1" geometry={nodes.SOLID008_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID008_2" geometry={nodes.SOLID008_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="15" position={[0.0111569315, 0.00085, -0.0071822554]} rotation={[0, 1.5705346837, 0]} userData={{ name: '15' }}>
          <group name="=>0113003" userData={{ name: '=>[0:1:1:3].003' }}>
            <mesh name="SOLID009" geometry={nodes.SOLID009.geometry} material={materials.mat_0} />
            <mesh name="SOLID009_1" geometry={nodes.SOLID009_1.geometry} material={materials.mat_1} />
          </group>
        </group>
        <group name="16" position={[0.0111653358, 0.00085, 0.0032477379]} rotation={[0, 1.5705346837, 0]} userData={{ name: '16' }}>
          <group name="=>0117002" userData={{ name: '=>[0:1:1:7].002' }}>
            <mesh name="SOLID010" geometry={nodes.SOLID010.geometry} material={materials.mat_4} />
            <mesh name="SOLID010_1" geometry={nodes.SOLID010_1.geometry} material={materials.mat_5} />
          </group>
        </group>
        <group name="17" position={[0.0111569315, 0.00085, -0.0032822564]} rotation={[0, -1.5705346837, 0]} userData={{ name: '17' }}>
          <group name="=>0117003" userData={{ name: '=>[0:1:1:7].003' }}>
            <mesh name="SOLID011" geometry={nodes.SOLID011.geometry} material={materials.mat_4} />
            <mesh name="SOLID011_1" geometry={nodes.SOLID011_1.geometry} material={materials.mat_5} />
          </group>
        </group>
        <group name="18" position={[0.0081469268, 0.00085, -0.007072255]} userData={{ name: '18' }}>
          <group name="=>01111001" userData={{ name: '=>[0:1:1:11].001' }}>
            <mesh name="SOLID012" geometry={nodes.SOLID012.geometry} material={materials.mat_0} />
            <mesh name="SOLID012_1" geometry={nodes.SOLID012_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID012_2" geometry={nodes.SOLID012_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="19" position={[0.0076269358, 0.00085, -0.0050822571]} rotation={[0, -1.5705346837, 0]} userData={{ name: '19' }}>
          <group name="=>01111002" userData={{ name: '=>[0:1:1:11].002' }}>
            <mesh name="SOLID013" geometry={nodes.SOLID013.geometry} material={materials.mat_0} />
            <mesh name="SOLID013_1" geometry={nodes.SOLID013_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID013_2" geometry={nodes.SOLID013_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="2" position={[-0.0091924667, 0.00085, -0.0072380602]} rotation={[0, -1.5705346837, 0]} userData={{ name: '2' }}>
          <group name="=>0113" userData={{ name: '=>[0:1:1:3]' }}>
            <mesh name="SOLID" geometry={nodes.SOLID.geometry} material={materials.mat_0} />
            <mesh name="SOLID_1" geometry={nodes.SOLID_1.geometry} material={materials.mat_1} />
          </group>
        </group>
        <group name="20" position={[0.0086169392, 0.00085, 0.0046777427]} rotation={[0, 1.5705346837, 0]} userData={{ name: '20' }}>
          <group name="=>01111003" userData={{ name: '=>[0:1:1:11].003' }}>
            <mesh name="SOLID014" geometry={nodes.SOLID014.geometry} material={materials.mat_0} />
            <mesh name="SOLID014_1" geometry={nodes.SOLID014_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID014_2" geometry={nodes.SOLID014_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="22" position={[-0.0000346601, 0.00085, -0.0000376552]} rotation={[0, 1.5705346837, 0]} userData={{ name: '22' }}>
          <group name="=>01113" userData={{ name: '=>[0:1:1:13]' }}>
            <mesh name="COMPOUND" geometry={nodes.COMPOUND.geometry} material={materials.mat_9} />
            <mesh name="COMPOUND_1" geometry={nodes.COMPOUND_1.geometry} material={materials.mat_10} />
            <mesh name="COMPOUND_2" geometry={nodes.COMPOUND_2.geometry} material={nodes.COMPOUND_2.material} />
          </group>
        </group>
        <group name="23" position={[0.0086169392, 0.00085, -0.0050822571]} rotation={[0, 1.5705346837, 0]} userData={{ name: '23' }}>
          <group name="=>0113004" userData={{ name: '=>[0:1:1:3].004' }}>
            <mesh name="SOLID015" geometry={nodes.SOLID015.geometry} material={materials.mat_0} />
            <mesh name="SOLID015_1" geometry={nodes.SOLID015_1.geometry} material={materials.mat_1} />
          </group>
        </group>
        <group name="25" position={[-0.0112346709, 0.00085, -0.0000176579]} rotation={[0, -1.5705346837, 0]} userData={{ name: '25' }}>
          <group name="=>01115" userData={{ name: '=>[0:1:1:15]' }}>
            <mesh name="SOLID016" geometry={nodes.SOLID016.geometry} material={materials.mat_7} />
            <mesh name="SOLID016_1" geometry={nodes.SOLID016_1.geometry} material={materials.mat_11} />
            <mesh name="SOLID016_2" geometry={nodes.SOLID016_2.geometry} material={materials.mat_12} />
          </group>
        </group>
        <group name="27" position={[0.007956937, 0.00085, 0.0084077418]} userData={{ name: '27' }}>
          <group name="=>01117" userData={{ name: '=>[0:1:1:17]' }}>
            <mesh name="SOLID017" geometry={nodes.SOLID017.geometry} material={materials.mat_3} />
            <mesh name="SOLID017_1" geometry={nodes.SOLID017_1.geometry} material={materials.mat_2} />
            <mesh name="SOLID017_2" geometry={nodes.SOLID017_2.geometry} material={materials.mat_13} />
          </group>
        </group>
        <group name="28" position={[-0.0098730624, 0.00085, -0.0000376552]} rotation={[0, 1.5705346837, 0]} userData={{ name: '28' }}>
          <group name="=>01111004" userData={{ name: '=>[0:1:1:11].004' }}>
            <mesh name="SOLID018" geometry={nodes.SOLID018.geometry} material={materials.mat_0} />
            <mesh name="SOLID018_1" geometry={nodes.SOLID018_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID018_2" geometry={nodes.SOLID018_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="29" position={[0.0076269358, 0.00085, 0.0046777427]} rotation={[0, -1.5705346837, 0]} userData={{ name: '29' }}>
          <group name="=>01111005" userData={{ name: '=>[0:1:1:11].005' }}>
            <mesh name="SOLID019" geometry={nodes.SOLID019.geometry} material={materials.mat_0} />
            <mesh name="SOLID019_1" geometry={nodes.SOLID019_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID019_2" geometry={nodes.SOLID019_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="3" position={[-0.0047030598, 0.00085, -0.0072422549]} rotation={[0, -1.5705346837, 0]} userData={{ name: '3' }}>
          <group name="=>0113001" userData={{ name: '=>[0:1:1:3].001' }}>
            <mesh name="SOLID001" geometry={nodes.SOLID001.geometry} material={materials.mat_0} />
            <mesh name="SOLID001_1" geometry={nodes.SOLID001_1.geometry} material={materials.mat_1} />
          </group>
        </group>
        <group name="30" position={[0.0096169263, 0.00085, 0.0046777427]} rotation={[0, 1.5705346837, 0]} userData={{ name: '30' }}>
          <group name="=>0113005" userData={{ name: '=>[0:1:1:3].005' }}>
            <mesh name="SOLID020" geometry={nodes.SOLID020.geometry} material={materials.mat_0} />
            <mesh name="SOLID020_1" geometry={nodes.SOLID020_1.geometry} material={materials.mat_1} />
          </group>
        </group>
        <group name="31" position={[0.0111653358, 0.00085, 0.0000145435]} rotation={[0, 1.5705346837, 0]} userData={{ name: '31' }}>
          <group name="=>01115001" userData={{ name: '=>[0:1:1:15].001' }}>
            <mesh name="SOLID021" geometry={nodes.SOLID021.geometry} material={materials.mat_7} />
            <mesh name="SOLID021_1" geometry={nodes.SOLID021_1.geometry} material={materials.mat_11} />
            <mesh name="SOLID021_2" geometry={nodes.SOLID021_2.geometry} material={materials.mat_12} />
          </group>
        </group>
        <group name="32" position={[0.0065969378, 0.00085, -0.0050822571]} rotation={[0, 1.5705346837, 0]} userData={{ name: '32' }}>
          <group name="=>01111006" userData={{ name: '=>[0:1:1:11].006' }}>
            <mesh name="SOLID022" geometry={nodes.SOLID022.geometry} material={materials.mat_0} />
            <mesh name="SOLID022_1" geometry={nodes.SOLID022_1.geometry} material={materials.mat_7} />
            <mesh name="SOLID022_2" geometry={nodes.SOLID022_2.geometry} material={materials.mat_8} />
          </group>
        </group>
        <group name="4" position={[0.0038377345, 0.00085, 0.0069649443]} rotation={[0, -1.5705346837, 0]} userData={{ name: '4' }}>
          <group name="=>0113002" userData={{ name: '=>[0:1:1:3].002' }}>
            <mesh name="SOLID002" geometry={nodes.SOLID002.geometry} material={materials.mat_0} />
            <mesh name="SOLID002_1" geometry={nodes.SOLID002_1.geometry} material={materials.mat_1} />
          </group>
        </group>
        <group name="6" position={[0.0036869347, 0.00085, -0.0083022565]} rotation={[0, -1.5705346837, 0]} userData={{ name: '6' }}>
          <group name="=>0115" userData={{ name: '=>[0:1:1:5]' }}>
            <mesh name="SOLID003" geometry={nodes.SOLID003.geometry} material={materials.mat_2} />
            <mesh name="SOLID003_1" geometry={nodes.SOLID003_1.geometry} material={materials.mat_3} />
          </group>
        </group>
        <group name="8" position={[-0.0112346709, 0.00085, 0.0032477379]} rotation={[0, 1.5705346837, 0]} userData={{ name: '8' }}>
          <group name="=>0117" userData={{ name: '=>[0:1:1:7]' }}>
            <mesh name="SOLID004" geometry={nodes.SOLID004.geometry} material={materials.mat_4} />
            <mesh name="SOLID004_1" geometry={nodes.SOLID004_1.geometry} material={materials.mat_5} />
          </group>
        </group>
        <group name="9" position={[-0.0112346709, 0.00085, -0.0033532605]} rotation={[0, -1.5705346837, 0]} userData={{ name: '9' }}>
          <group name="=>0117001" userData={{ name: '=>[0:1:1:7].001' }}>
            <mesh name="SOLID005" geometry={nodes.SOLID005.geometry} material={materials.mat_4} />
            <mesh name="SOLID005_1" geometry={nodes.SOLID005_1.geometry} material={materials.mat_5} />
          </group>
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Jacdac_RotaryModule.gltf')
